### ISSUE TITLE
Scene Freezing in Scene 6 [Fixed?]

### ISSUE THREAD

**Issue by Elithanathile** [07th-mod/onikakushi#100]
So while playing this patched version of Onikakushi, I came upon an error where the textbox and GUI would disappear, leaving only the background and sprites there, but I couldn't go forward or access any menus. When closing the window though, it would still prompt me if I wanted to exit.

I got this problem once in a tip scene, but just skipped the tip. I really ran into problems when I got the same error during chapter 6, just after letting the cotton float down the river.

So I reinstalled. And got the same problem. So I reinstalled again. Same thing. I used the manual patch. Nope.

To make a much longer story short, I eventually found out that it was trying to load a sprite and couldn't find it. "ta_si_de_a1" to be exact. (Thanks to the "LINUX - Game Hang on Chapter 7" Issue) So after a little more trial and error, I went through the script files to find the correct section and located which sprite it wanted to load, the aforementioned one.

I finally located the sprite in the "night" folder of the CGAlt (Using the updated sprites, the original ones would be in the CG folder) I don't know if it's a problem with the patch, my computer, or the installation, but the script wasn't going into that folder to find the files, and since many of the sprite files shared names with their standard versions, it was usually using the normal lighting ones. But when there was a sprite that only existed at night, it was helpless.

So my fix was just to copy all the files from the night folder into the CGAlt folder and choose "don't copy" when it said there were files with duplicate names. So I got the needed files and it works now, but there's still the issue of sprites that should be using the "night" or "sunset" versions just using the basic sprite.

And I didn't go back and check the tip I had the same issue on, so that might not have fixed that.

Figured I'd post this here to help anyone else out who had the same problem without them having to spend hours trying to figure this out, and just in case the patch developers weren't aware of this bug(?).

**Comment by ItaloKnox** [comment]
Just clear something up for me: are you running Linux? If that's the case we're aware of this issue and going to fix it in the next version that should be coming soon.

**Comment by Elithanathile** [comment]
Nope, this was on Windows 7 x64, Professional Edition. Meant to have that in my first post, but forgot.

**Comment by ItaloKnox** [comment]
I looked around and the sprite is definitely missing in our graphics patch. It only comes up in the night folder like you said. Can you give more clues on where the line with this sprite can be found? Any text prior this or after will do.

**Comment by Elithanathile** [comment]
Scripts, "onik_009_02", the phrase directly before the problem is "...I felt a little like I was intruding."

The line directly after is "How was it, Keiichi-kun?"

**Comment by ItaloKnox** [comment]
I'm even more confused now. All the calls go directly to ``night/ta_si_de_a1``, which actually exists in the CG folder. You said it also exists in the CGAlt folder, both cases inside the night subdirectory. Even if the file didn't exist inside the CGAlt folder, it exists in the CG folder. In this case, the game would use the CG folder as a fallback for the nonexistent file.

Can you give this issue a read @P-Chang @enumag? I think I'm missing something crucial here.

**Comment by Elithanathile** [comment]
Yours shows "night/ta_si_de_a1" in the script file? Mine just has "DrawBustshotWithFiltering( 1, "ta_si_de_a1", "left", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );" for that line. And I couldn't see anywhere in the script file that it did say to take sprites from the night folder. Is this just my installation, or am I missing where it directs it there?

**Comment by ItaloKnox** [comment]
I'm looking directly from the latest commit in the repository. Should be [here](https://github.com/07th-mod/onikakushi/commit/9a066ac17c6219347e4e97197fc25186996b4bba).

Where did you get the patch?

**Comment by Elithanathile** [comment]
I got the patch from you guys, the installer in the guide page. I tried the manual installation as well, but that one had some kind of issue so it didn't work for me. The only spot that had actual script files that I saw though was in the 4.0.1 voice and graphics patch, inside an "Updates" folder. So I followed the instructions and added the folder to the StreamingAssets, even though there wasn't an Updates folder already there. 

Just checked the voice and graphics patch files, and the Updates folder does look like scripts. I found the right script, and it does navigate to "night/ta_si_de_a1" for that. So did I just mess up the installation somehow? When I use the installer there's no Updates folder in StreamingAssets, but apparently it's using different script files than the patch as well, so it didn't merge those into the Scripts folder.

**Comment by ItaloKnox** [comment]
Do you have a CompiledUpdateScripts folder? I think you're running an older version of the game and because of that, it doesn't load the files of the Updated folder. Does your game even have voices at all?

**Comment by Elithanathile** [comment]
It has a CompiledScripts folder, but not CompiledUpdatedScripts. And no, I don't have voices. I just assumed it was like some other games and only had those for cutscenes or something. I spend another few installs-reinstalls trying to get those working before settling for what I have.

I get the feeling that this is what the problem is.

**Comment by ItaloKnox** [comment]
Yeah, the game is not updated. The game is fully voiced, you just played the whole thing with the graphics swapped. If you actually downloaded the patch in a week or two it wouldn't even boot at all since we're changing all the filenames.

Considering you have the MangaGamer DRM-free version, you should just go to the store and download the latest build. We asked them to update it last month to make it fully compatible since one of the builds was really outdated.

**Comment by Elithanathile** [comment]
Well, I guess if anyone else has the old version, this thread can helpfully show them what the problem is.

Aha, sorry for wasting your time then! I'll probably try that out and make sure it works tomorrow before closing this issue then. Thanks for the help!

**Comment by ItaloKnox** [comment]
Sure, don't worry about that. That actually happens more often than you thought.
Give me a heads up if you need anything! 👍
