### ISSUE TITLE
Higurashi Font List + Fonts

### ISSUE THREAD

**Issue by InochiPM** [07th-mod/onikakushi#102]
So i have slowly been compiling a list of all of the fonts used for the higurashi logos, text for the poems and such. 
[Higu-FontLIST.txt](https://github.com/07th-mod/onikakushi/files/1662642/Higu-FontLIST.txt)
Heres the list of fonts so far, but im gonna mark them all down here just incase no one wants to look into the Txt file.

Font's I have found:
- Higurashi When They Cry Logo - _SeiKaiCB1Std-Regular/A-OTF 正楷書CB1 Std Regular_
- Higurashi When They Cry Kai Logo - _ReishoE1/隷書E1_
- Higurashi/Kai/Rei/Hou Japanese Logo -  _Arisawa-Kaisho/有澤楷書_
- Higurashi Chikai (Live Action Movie) - _DF Shonan-gyoshotai Std W5/DF祥南行書体 Std W5_
- Higurashi Sui Grungy Red Text - _Tb Ko Shirushi-tai/TB古印体_
- Higurashi Sui Poems-TextCG - _リュウミン M-KO/AR Dabiaosong_ 
**(These two fonts are used together, the first one is only romaji+katakana and AR is kanji only. So we could substitute a nice handwritten font for this altogether. )**

Fonts i still need to find:
1. **Higurashi Sui Logo** - Gotta find the font used for the Sui part of the logo.
2. **Higurashi Kizuna Logo** - Gotta find the font used for the Kizuna part of the logo. (Probably the same as Sui's logo font)
3. **Higurashi Matsuri Logo** - Gotta find the font used for the Matsuri symbol, im pretty sure its a font they still use, since i saw some similar looking font used in one of the openings for Sui. 
4. **Higurashi Jan Logo** - Gotta find this one to, though i think it may be an edited symbol from the font used for Chikai. 

Heres the font zipfile for people who want them just to have them or for remaking the logos if needed. 
[Higurashi_Fonts.zip](https://github.com/07th-mod/onikakushi/files/1662654/Higurashi_Fonts.zip)

**Comment by ItaloKnox** [comment]
The bot seems to be working, lol.

I'll just get rid of it for this issue. 🤣
