### ISSUE TITLE
New graphics patch

### ISSUE THREAD

**Issue by enumag** [07th-mod/onikakushi#103]
@ItaloKnox Alright, your turn. Ask me if anything is unclear.

### Download resouces

- 1440p PS3 weather sprites from Iri
    - https://mega.nz/#!v80FAbxS!BQdOrCTbR98Yf1FTM-DXiZUEcAj0l0evSP5Ve3wRplg
- 1440p non weather sprites from our resources repo
    - https://github.com/07th-mod/resources/releases/download/Nipah/Higurashi-Portraits-1440p.7z
    - https://github.com/07th-mod/resources/releases/download/Nipah/Higurashi-Sprites-1440p.7z
- 1080p PS3 backgrounds
    - https://github.com/07th-mod/resources/releases/download/Nipah/Higurashi-Graphics-1080p.zip.001
    - https://github.com/07th-mod/resources/releases/download/Nipah/Higurashi-Graphics-1080p.zip.002
- old graphics patches for onikakushi
- shell scripts to compile the new patch
    - https://www.dropbox.com/s/n5qzucaftki48ti/onikakushi.sh?dl=0

## Unzip

When you download and unzip everything, the directory structure should look like this:

```
onikakushi-old/
    CG/
    CGAlt/
ps3/ (Higurashi-Graphics-1080p.zip)
sprites/ (Iri's 1440p weather sprites)
    Night/
        l/
        m/
    Sunset/
        l/
        m/
    Normal/
        l/ (images from Higurashi-Portraits-1440p.7z)
        m/ (images from Higurashi-Sprites-1440p.7z)
onikakushi.sh
```

Doublecheck that you have the structure correctly. It's easy to make it like `sprites/Normal/m/m/aka_Def_0.png` instead of `sprites/Normal/m/aka_Def_0.png`.

### Compile

Now you just run the shell sript. It will create new directory with the new patch. The patch should be compatible with the lip-sync branch in this repo.

You might see some errors like `cp: cannot stat 'himatsubushi-old/CGAlt/oryou_Def_0.png': No such file or directory` - **post these error here for my review please.**

### Post-compilation

Manually add the textboxes from https://github.com/07th-mod/resources/releases/download/Nipah/Higurashi-Textboxes.zip to the CG directory of the compiled patch.

Manually add the files for the PS3 poem from https://www.dropbox.com/s/jzwjelnh7yzj6bd/CG.zip?dl=0 to the CG/text directory of the compiled patch.

Manually merge *the contents* of `pack` directory from [this file](http://www.mediafire.com/file/zi722s1wsrmb1ia/pack2.rar) into the CG directory.

FInally add this image into the CG directory: https://cdn.discordapp.com/attachments/384427950478589972/407293451055529985/alphaimage.png

Upload the compiled CGAlt directory somewhere and send a link to jwgrlrrajn. He'll change some images using his new night filter and send them back to you. When he does, replace the images in CGAlt with his.

This should be everything. Now you can zip and upload the new patch.

### Voice patch

Add the voices from this file to the voice patch (ignore the CG directory). http://www.mediafire.com/file/cbqujpn0ccqukqa/OniPoem.rar

Add spectrum files to the voice patch. http://www.mediafire.com/file/qlc4hgb9265glhz/ch1_spectrum.rar

The directory structure should look like this:

```
voice/
    s##/
    s##/
spectrum/
    s##/
    s##/
```

Oh and add the missing files from our repo. Don't ignore this step - I added some voices last week. https://github.com/07th-mod/onikakushi/archive/master.zip

### New DLL patch

http://www.mediafire.com/file/zoylo9o7oc81q81/chapter1dlls_v4.x.x.rar

**Comment by ItaloKnox** [comment]
Just started working on this. Should take some time since mega is awfully slow today.

**Comment by ItaloKnox** [comment]
Ok, just finished the first part. Got these errors, double check them for me before I keep going:
```
cp: cannot stat 'onikakushi-old/CG/monologue_oni1.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni2.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/kuma_Def.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/kuma_Ikari.png': No such file or directory
```

**Comment by enumag** [comment]
@ItaloKnox These are ok. Kuma does not have steam sprites.

**Comment by ItaloKnox** [comment]
Nice, I'll be pushing them to the repo in a bit. What about the moving backgrounds/CGs? Will we skip them?

**Comment by enumag** [comment]
@ItaloKnox P-Chang said he will do them later - after the pre-release.

**Comment by P-Chang** [comment]
@enumag 
What? didn't you ask me to implement until pre-release?

**Comment by ItaloKnox** [comment]
New files are on the [Hanyuu](https://github.com/07th-mod/resources/releases/tag/Hanyuu) tag. I'll leave it like this without a release until we decide if it'll be implemented now or later.

**Comment by enumag** [comment]
@P-Chang I did not. https://github.com/07th-mod/higurashi-patch-compiler/issues/24#issuecomment-359209929

**Comment by P-Chang** [comment]
@enumag 
Oh, I misunderstood. Sorry.

this topcis was rebooted in discord, and I confirm background resolution is 1080p.
So, I though decision was changed.

I can push them with some tweak after coming upscaled one.
What should I do?

**Comment by enumag** [comment]
Upscaled images are in the 1080p pack in resources. If you have those then I'm not sure what you're asking. Catch me on Discord later to clarify. Thanks for your hard work!

**Comment by enumag** [comment]
@ItaloKnox Did you send the CGAlt directory to @jwgrlrrajn? (Just confirming that everyone has what they need to work.)

**Comment by ItaloKnox** [comment]
Not really, sorry. Got sidetracked a bit because Dragon Ball FighterZ was just released. 😆

**Comment by enumag** [comment]
@ItaloKnox Ah, enjoy that then! 😄

**Comment by P-Chang** [comment]
New pack have too much missing upscaled vanilla stuff.

**Comment by enumag** [comment]
I'll look into it when I wake up. Going to bed now.

**Comment by enumag** [comment]
@P-Chang Thanks. I fixed those issues.

@ItaloKnox I will need you to rerun the shell script later but I'm still gathering the resources. Also I need your opinion [here](https://github.com/07th-mod/higurashi-patch-compiler/issues/26).

**Comment by jwgrlrrajn** [comment]
Updated all the night filter sprites, and added one of the missing sunset sprites.

https://drive.google.com/open?id=1jLtrFY6C3vu08pXDvto4BorQAKL5OmWT

**Comment by ItaloKnox** [comment]
@jwgrlrrajn Can't you push that to the Hanyuu tag I posted above? I can do it if you don't want to. Usually, Google Drive links are a bother to download with the server and push them on the tag.

**Comment by enumag** [comment]
@ItaloKnox So in the last week @P-Chang made some improvements and reported some issues in the compiler. Everything should be fixed now but I need you to recompile the patch.

You don't need to redownload anything except for the sh file: https://www.dropbox.com/s/n5qzucaftki48ti/onikakushi.sh?dl=0

Delete the previously generated `onikakushi` directory and run the shell script (post errors here for my review, there will be more of them this time but they should be all false positives).

Then reapply all the manual additions (poems and such).

Then manually merge the pack directory from [this file](http://www.mediafire.com/file/zi722s1wsrmb1ia/pack2.rar) into the CG directory.

Then add this image into the CG directory: https://cdn.discordapp.com/attachments/384427950478589972/407293451055529985/alphaimage.png

That should be everything. Pack and upload the CG directory to resources and let me know.

You don't need the newly generated CGAlt directory, just use what @jwgrlrrajn sent you.

Sorry it took me so long. I was more busy then expected this week.

**Comment by ItaloKnox** [comment]
Here they are:
```
cp: cannot stat 'onikakushi-old/CG/black_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/white_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/cinema_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_1.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_1_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_2.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_2_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_3.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_3_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_4.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_4_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/alphaimage.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/alphaimage_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/004b.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/004b_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/sunset/re_se_bi_a1.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni1.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni1_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni2.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni2_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/002a.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/002a_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/002b.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/002b_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/text/oni_usoda.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/text/oni_usoda_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/031.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/031_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/004.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/004_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/append/waku_b.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/append/waku_b_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/eye.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/eye_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/kuma_Def.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/kuma_Ikari.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/ex_otsu_j.png': No such file or directory
```

I'll be doing what's left and upload the new version in the meantime.

**Comment by enumag** [comment]
I confirm that these are all false-positives.

**Comment by ItaloKnox** [comment]
Not really sure about where to put the ``pack`` directory. Should I put it inside ``CG`` or only the subfolders inside it?

**Comment by P-Chang** [comment]
Sorry,  put it like

CG\overview
CG\text

**Comment by ItaloKnox** [comment]
![firefox_2018-01-28_21-18-05](https://user-images.githubusercontent.com/4702556/35488469-ba3b4b60-0470-11e8-8506-90276bafbe95.png)

Like that, I guess?

**Comment by ItaloKnox** [comment]
Ok, just uploaded all the new files including the one I was @jwgrlrrajn to upload before. We're all set, I guess.

**Comment by P-Chang** [comment]
Yes.

Anyway, these are all? may be some mask texture still missing?

**Comment by ItaloKnox** [comment]
That's all we have in the root folder, everything else should be inside the folders unless @enumag forgot to tell me something.

**Comment by enumag** [comment]
@ItaloKnox Thanks. I have a script to detect mistakes, I'll run it when I get home.

> may be some mask texture still missing?

@P-Chang Only if they're used directly by the engine and not in the scripts. Which might be possible. Maybe we should just force-copy all mask images from the old patch?

**Comment by P-Chang** [comment]
in this case, third argument "left" is sprite name.

`DrawBustshotWithFiltering( 1, "re_se_wa_b1", "left", 1, -160, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );`

**Comment by enumag** [comment]
@P-Chang Oh. Ok, that's a bug then. Do all `WithFiltering` work like this?

**Comment by P-Chang** [comment]
Sure it is same.

Although, I don't know why 
`DrawSprite( 5, "Meakasi_List", NULL, -320, -240, 0, 0, 0, 0, FALSE, FALSE, 0, 0, 32, 100, TRUE );`

third NULL may be mask, but currently it is not used.

**Comment by enumag** [comment]
@P-Chang Since it's not used I'll ignore it.

----

Ok I looked into our current onikakushi patch. There are some files that might or might not be used by the engine. I'm not sure which of these I should force-copy to the new patch. What do you guys think? Things like up/down/right/left/x/2/4/5/black/white are obvious. Some others should probably be removed - title_j and ex_wata. I'm not completely sure about some of the others like haikei, ex_jump, logo, mangagamer... Any ideas?

https://www.dropbox.com/s/gkmt8d7m6ic9vgi/CG%20-%20Copy.zip?dl=0

**Comment by P-Chang** [comment]
almost of them is used in only flow.txt and oni patch doen't have it.

title_j and ex_wata may be garbage from ancient non Unity version.

**Comment by enumag** [comment]
@P-Chang Thanks.

@ItaloKnox Really sorry about all of these issues. Can you recompile it again and reapply the manual things? I added all the manual steps to the first post. Also monologue_* images belong to `CG/text`, fixed that in the first post too. Again don't worry about CGAlt but post the errors here for my review.

Here is the latest bash file you should use:

https://www.dropbox.com/s/n5qzucaftki48ti/onikakushi.sh?dl=0

**Comment by ItaloKnox** [comment]
Sure, going to work on it right now. Might be just enough time to finish Lizard on my King Crimson journey. 🤣

**Comment by ItaloKnox** [comment]
Here are the errors from this run:

```
cp: cannot stat 'onikakushi-old/CG/black_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/m1_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/right_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/left_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/white_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/up_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/x_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/cinema_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/c_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_1.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_1_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_2.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_2_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_3.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_3_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_4.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/overview/hina1_4_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/alphaimage.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/alphaimage_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/down_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/mask_1900_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/004b.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/004b_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/sunset/re_se_bi_a1.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni1.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni1_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni2.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/monologue_oni2_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/aa_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/002a.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/002a_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/002b.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/002b_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/text/oni_usoda.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/text/oni_usoda_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/031.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/031_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/004.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/004_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/append/waku_b.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/append/waku_b_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/eye.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scene/eye_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/kuma_Def.png': No such file or directory
cp: cannot stat 'onikakushi-old/CGAlt/kuma_Ikari.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/ex_otsu_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/5_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/2_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/4_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/Title02_j_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/centerblind_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/end_1_j_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/end_2_j_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/end_3_j_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/ex_jump_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/ex_tips_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/haikei-_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/haikei_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/logo_j_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/logomask_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/mangagamer_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/mask1013_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/no_data_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scenario_a_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scenario_b_j_j.png': No such file or directory
cp: cannot stat 'onikakushi-old/CG/scenario_c_j_j.png': No such file or directory
```

**Comment by ItaloKnox** [comment]
New build should be already available. 😄

**Comment by enumag** [comment]
@ItaloKnox Wow you're fast. 😄 My debug script only reported these:

```
File CG/alphaimage.png not found.
File SE/s01/11/120700246.ogg not found.
File CGAlt/sprite/normal/kuma_def_0.png not found.
File CGAlt/sprite/normal/kuma_komaru_0.png not found.
```

The last two are false-positives but apparently you forgot to add the alphaimage.png file and the missing voice I recently added. You can fix that by adding the CG/alphaimage.png into our onikakushi repo instead if you don't want to reupload the zips.

Aside from that we should be ready for pre-release, But someone should probably test the game first a little to see if there is any obvious issue.

**Comment by ItaloKnox** [comment]
Oops, you're right about the first one. I downloaded it but forgot to move to the folder. I'll redo it.

**Comment by ItaloKnox** [comment]
There you go, both voices and CG reuploaded with the missing files. Should be ready to go now.

**Comment by enumag** [comment]
@ItaloKnox I forgot to tell P-Chang that we were waiting for fixed DLL (with lip-sync enabled by default) hence the delay. He just sent the DLL to me now. With this I believe you can make the Oni pre-release whenever you have time. :-)

https://cdn.discordapp.com/attachments/403224214145859585/408922081284063232/fixed.rar

**Comment by jwgrlrrajn** [comment]
Trying to resize the MG resources' dimensions to match their PS3 counterparts, and Mion's swimsuit sprites caught my attention. They're a fair bit more form fitting than their PS3 renditions, to put it mildly. So, before I recompile the CG-Alt folder, I was wondering which version people thought was better.

http://screenshotcomparison.com/comparison/130931

**Comment by enumag** [comment]
Personally I'm ok with either.

**Comment by enumag** [comment]
@jwgrlrrajn I discussed it with @ItaloKnox - we'll use the updated version. Which chapters is this for? Just Meakashi, right?

**Comment by jwgrlrrajn** [comment]
Onikakushi, actually. Speaking of, I finished making the 1440p versions of Onikakushi's MG sprites, updated Mion included. I've uploaded them as Onikakushi-CGAlt-1440p.7z to differentiate them from the current sprites.
