### ISSUE TITLE
Rena's graphic fades in instead of Mion

### ISSUE THREAD

**Issue by odacaesar** [07th-mod/onikakushi#105]
During the line on the first schoolday when Mion says about not needing to pass an entrance exam to get to university: "That is right.  There aren't really enough people out here to warrant weeding people out with an exam."  Mion fades back in after that line; when it should be that Mion already faded in for that line, and Rena fades back in for the next line,

I am running it from Steam on Windows 7, 64-bit, with a manual installation of all mods.

**Comment by ItaloKnox** [comment]
Can you tell me if you are running the lipsync update (v5.0.2-beta) or the latest stable update (v4.0.1)?

**Comment by odacaesar** [comment]
v4.0.1

**Comment by ItaloKnox** [comment]
I think @enumag might be able to see if this was already fixed or not.

**Comment by temp-user527** [comment]
Hello,
I can confirm the bug in the current stable patch. Select Day 1 in the Chapter Jump.
Here is the screen in question: https://i.imgur.com/ZGGUpeP.jpg
And here is the screen right after: https://i.imgur.com/LwgsHxd.jpg

**Comment by idealpersona** [comment]
Thank you for the report.

Confirmed caused here in the script: https://github.com/07th-mod/onikakushi/blob/3f70887f28ec79e32820bbd4ff9e8f38b7d587c9/Update/onik_001.txt#L2837

**Comment by enumag** [comment]
Fixed. Thanks for reporting.
