### ISSUE TITLE
Onikakushi - Sui Edits

### ISSUE THREAD

**Issue by InochiPM** [07th-mod/onikakushi#106]
So i have been playing around and learning how to use and edit the scripts for Oni since thats the first chapter. Along with making a few other edits here and there. 
I'm going to post the majority of my edits i made to the scripts here for others to look at and test out just incase we end up using them. 

[flow.txt](https://github.com/07th-mod/onikakushi/files/1756917/flow.txt)
[onik_op.txt](https://github.com/07th-mod/onikakushi/files/1756918/onik_op.txt)

Please make sure to make backups of the original Flow.txt and onik_op.txt just incase they dont work you can revert.

To use/test these scripts you have to have the alpha build of oni with the new folder structure. 
When applying the CG make sure to leave the files inside of the New_CG folder in the CG folder because the flow file picks from the CG folder not the background folder. 
Make sure to place the sora1 file in the backgrounds. 
SE and BGM go in their respective folders.
TIPS go in the text folder along with the text images in the CG folder. 

[New_CG.zip](https://github.com/07th-mod/onikakushi/files/1756914/New_CG.zip)
[SE_BGM.zip](https://github.com/07th-mod/onikakushi/files/1756912/SE_BGM.zip)
[TIPS_CG.zip](https://github.com/07th-mod/onikakushi/files/1756913/TIPS_CG.zip)

**Comment by enumag** [comment]
I'm going over your changes here. I'm not entirely sure about the SE and BGM changes. Until now we never really touched SE and BGMs so I feel like we should maybe stick to that and later make another patch that would change those to Sui. Using just 5 sui files and just in onikakushi isnt a best idea oif you ask me.

**Comment by enumag** [comment]
Just to be clear I do like the Sui sounds more than the current one, I just don't want to incorporate them now before a major release. I feel this should be a part of a bigger overhaul later on.

For now I'll merge these changes: https://github.com/07th-mod/onikakushi/commit/3f70887f28ec79e32820bbd4ff9e8f38b7d587c9

Images for tips will be used of course.

The smaller higu logos and the nodata image are good to use too.

Let's discuss BGM and SE changes later, ok?
