### ISSUE TITLE
Higurashi for switch on july

### ISSUE THREAD

**Issue by yagamisempai** [07th-mod/onikakushi#108]
![29472163_573040383078166_2211368453487565310_n](https://user-images.githubusercontent.com/28794338/37751244-99cbafb0-2d91-11e8-8316-8659efac2165.jpg)
![29472537_573040399744831_6551685565831279076_n](https://user-images.githubusercontent.com/28794338/37751245-9a13c6a6-2d91-11e8-97cc-e21499ccdeb0.jpg)
![29498060_573040349744836_8985284033782261118_n](https://user-images.githubusercontent.com/28794338/37751247-9a42ba38-2d91-11e8-86df-1843abbe1304.jpg)
![29541043_573040229744848_8314849931459184939_n](https://user-images.githubusercontent.com/28794338/37751248-9aaa2862-2d91-11e8-8e43-4d69b6efb18a.jpg)

Will include all 19 arcs from sui plus the 3 higurashi hou arcs.
outbreack, kamikanshi nad hinamizawa bustop

http://www.siliconera.com/2018/03/20/higurashi-cry-hou-headed-nintendo-switch-japan-july-26/#P9oyOixDURyBaJyZ.16

**Comment by ItaloKnox** [comment]
Yeah, everyone in the Discord channel is pretty hyped for this. We now have sprites for all chapters, so that's a good thing. We're also paying attention to see if we can get upgraded assets from the game.

**Comment by enumag** [comment]
We're tracking this in the compiler repo. Closing here.
