### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by iriyap** [07th-mod/onikakushi#109]
Here are some of the typos I've come across during my Onikakushi playthrough:
https://steamuserimages-a.akamaihd.net/ugc/938308370379612499/B4C8103F600EBB4E3F6BFDE1A5E3AE8C99C9B663/
https://steamuserimages-a.akamaihd.net/ugc/938308370379612768/37BB74C0B958725905A1AF7892725CC07B5501DA/
https://steamuserimages-a.akamaihd.net/ugc/938308731264129246/7C805F6800C93DB0BC943AB5338154E29DD23639/
https://steamuserimages-a.akamaihd.net/ugc/938308370377740671/87183AA3DECAE22887792E8E9B9000CF3A4EB2C7/

**Comment by enumag** [comment]
All fixed. Thank you!
