### ISSUE TITLE
Allowance Money: Dollar -> Yen

### ISSUE THREAD

**Issue by iriyap** [07th-mod/onikakushi#110]
For some reason, the very first time money is brought up in the game MangaGamer localized it as US Dollars, so 1000 yen was translated to 10 dollars. In all other instances Yen is used, which is of course more sensible for a remote Japanese village in the 1980's. IMO, it wouldn't hurt to fix this minor slip-up especially since it's been mentioned in a few negative Steam reviews.

**Comment by enumag** [comment]
Can zou be more specific where this occurs? I only found one instande of "dollar" being used in Onikakushi but it was 1 dollar instead of 100 yen (https://github.com/07th-mod/onikakushi/commit/e9eeee00bd014a87458bcf8ebfee5378ac37034a) so it's different instance than the 10 dollas you mentioned.

**Comment by iriyap** [comment]
That's probably it, I must have misremembered an extra zero. Didn't screenshot it at the time, so eventually forgot the specifics.

**Comment by enumag** [comment]
Alright, closing then. Thank you!
