### ISSUE TITLE
Text & Voice Issues in Ch. 4

### ISSUE THREAD

**Issue by mfdsrax2** [07th-mod/onikakushi#113]
Censored texts.
![inked20180329004059_1_li](https://user-images.githubusercontent.com/13324717/38128893-7441a2c4-33b1-11e8-9b22-5f8212c3a6ab.jpg)
![20180329004209_1](https://user-images.githubusercontent.com/13324717/38128925-90375cf8-33b1-11e8-85ba-f933714a42d4.jpg)

Text split here.
Another problem is that when using quotation marks inside another quotation marks, Japanese usually uses a different mark, like 「『アレ』は英語で何と言う〜？！？！」. I think there should be examples in previous texts but I can't find them.
![inked20180329004228_1_li](https://user-images.githubusercontent.com/13324717/38129020-0ac17774-33b2-11e8-9edb-e6389b77202a.jpg)

Incorrect text display here. There's even a '>' mark at the end of the dialog.
![20180329005522_1](https://user-images.githubusercontent.com/13324717/38129163-abbdfa76-33b2-11e8-8090-50b20e7b0a44.jpg)
![20180329005552_1](https://user-images.githubusercontent.com/13324717/38129168-b24de34c-33b2-11e8-84df-37e7debd25d7.jpg)

Issues in TIPS 07
When Satoko talks about Rena, she always uses 'Rena-san', at least what I heard is that.
So these texts should be 「レナさんですの？」「レナさんは日直だから」. English texts should also be like "Rena-san'.
![20180330001854_1](https://user-images.githubusercontent.com/13324717/38129366-9d90619a-33b3-11e8-9f5e-1509cc501ca4.jpg)
![20180330001947_1](https://user-images.githubusercontent.com/13324717/38129492-1ea632d2-33b4-11e8-85d9-accfa453752c.jpg)

This dialog should actually be 「レナさんが言ったのですわ。レナと呼んで欲しいって。だからレナさんなのですわ。」"Rena-san had told us that she wanted us to call her 'Rena.' So we call her Rena-san.\"
![20180330002040_1](https://user-images.githubusercontent.com/13324717/38129565-6e4b7bda-33b4-11e8-9f8d-9a0a9b8a6b4c.jpg)

The text paused halfway, but the voice didn't stop here.
![20180330002340_1](https://user-images.githubusercontent.com/13324717/38129617-a241168e-33b4-11e8-8d6e-dee424ba14de.jpg)

**Comment by Norgus** [comment]
I couldn't see a problem with the timing vs when the text appears on the last problem, but I've fixed the other issues.

**Comment by enumag** [comment]
@Norgus Timing issues were probably fixed by @orian34.
