### ISSUE TITLE
Text & Voice Issues in Ch. 5

### ISSUE THREAD

**Issue by mfdsrax2** [07th-mod/onikakushi#114]
A period is missing on the last line.
![20180331003846_1](https://user-images.githubusercontent.com/13324717/38161217-93132a46-347f-11e8-8975-b37fbdcbd3b1.jpg)

Actually Rena laughed like 「あへへ」 "Ahehe" instead of 「あはは」 "Ahaha" here. It's upon you to decide whether to change it or not since it's not a big issue.
![20180331004027_1](https://user-images.githubusercontent.com/13324717/38161248-1ed10bb6-3480-11e8-9a71-98ba1528413a.jpg)

The voice here is very short and I didn't hear it clearly. But I'm sure it does not match the text.
![20180331005823_1](https://user-images.githubusercontent.com/13324717/38161250-24a24758-3480-11e8-92c0-705f4b292a11.jpg)

I didn't finish this chapter yet. I'll keep updating.

**Comment by mfdsrax2** [comment]
Update

The voice here is incorrect.
![20180331215903_1](https://user-images.githubusercontent.com/13324717/38170157-7ba36e1c-3532-11e8-9721-21ef50e05e89.jpg)
![1](https://user-images.githubusercontent.com/13324717/38170165-98593316-3532-11e8-8784-53d92fb5f156.PNG)

The text got split on the last line.
![20180331221713_1](https://user-images.githubusercontent.com/13324717/38170178-efb8066e-3532-11e8-9883-27da792bc15b.jpg)

That should be all the issues I found in Ch. 5.

**Comment by Norgus** [comment]
Fixed except for the following two which I determined to be non-issues. Please correct me if I misunderstood.

あはは vs あへへ, the text is あはは in the PS3 game that the voice is sourced from, and I couldn't find precident for using あへへ or "ahehe" in the game script elsewhere, so leaving this one unchanged.

The last issue about text splitting doesn't seem like a problem to me. I think the English version of the text here would end up on at least 4 lines if it were forced into one box, which is undesirable.
