### ISSUE TITLE
CG Sprites Missing

### ISSUE THREAD

**Issue by orian34** [07th-mod/onikakushi#123]
No sprites for : 
"sprite/sunset/re1b_bikkuri_b1_"
"sprite/normal/me1b_ikari_a1_"
"sprite/normal/ri4_komaru_a1_"
"background/hi1"
"background/y_jt2"
"sprite/normal/sa2b_yareyare_b1_"
"sprite/normal/sa2b_akireru_b1_"
"sprite/normal/re2b_komaru_b2_"
"sprite/normal/sa2b_warai_b1_"
"sprite/night/re2a_kaii_a1_"
"portrait/normal/sa1a_akuwarai_a1_"
"portrait/normal/sa1b_naku_b1_"
"portrait/normal/re1a_komaru_a1_"
"portrait/normal/re1a_bikkuri_a1_"
"sprite/normal/re1a_okoru_a1_"
"portrait/normal/sa1b_akuwarai_b1_"
"sprite/normal/oisi1_3_"
"sprite/normal/sa1b_yareyare_b2_"

**Comment by enumag** [comment]
Hmm this is quite a few now. I'm thinking whether I should do this manually or write yet-another-script.
