### ISSUE TITLE
Exit to Menu

### ISSUE THREAD

**Issue by orian34** [07th-mod/onikakushi#152]
The "Exit to Menu" button doesn't correctly clean up filters by using FadeFilm. With results in any filter to stay until you encounter a FadeFilm command(which can never happen for some chapters). Resulting in pretty strange things.
![image](https://user-images.githubusercontent.com/12663654/38646883-11225e52-3dea-11e8-9fb2-cd20dbaba2f5.png)
![image](https://user-images.githubusercontent.com/12663654/38647054-a9664124-3dea-11e8-8202-9f559671a9f8.png)
![image](https://user-images.githubusercontent.com/12663654/38647065-b3ebac88-3dea-11e8-8a64-6b70f6496adf.png)

**Comment by idealpersona** [comment]
@orian34 Try this out.  It's not very graceful but it does fix it from my quick test.  You can install this in the `HigurashiEp01_Data\Managed` folder.  (make a backup of your existing `Assembly-CSharp.dll` first)

https://github.com/07th-mod/higurashi-dlls/raw/issue-oni-152/Onikakushi/Assembly-CSharp.dll

Did this issue happen if you loaded or quick-loaded a game while a film effect is on as well?  If so does this DLL solve it too?

**Comment by idealpersona** [comment]
@irlPM The fix was just proved out and hasn't yet been applied to Oni stable nor to any other arcs, but that's okay because I created an issue in higurashi-dlls for this.
