### ISSUE TITLE
Unflagged censorship in Day 1

### ISSUE THREAD

**Issue by idealpersona** [07th-mod/onikakushi#156]
A large chunk of the scene in day 1 with mion and Rena at the meetup point before school is censored without a flag.  It's all sexual jokes so I believe that should be at censor level 4.  

Example lines: https://github.com/07th-mod/onikakushi/blob/master/Update/onik_001.txt#L1072 https://github.com/07th-mod/onikakushi/blob/master/Update/onik_001.txt#L1123 
Original: `Not only is he bigger, but he has a little moustache now~☆`
Mod: `You've grown up so much, you even have a beard~!`

Credit to @Petsnew for finding this.

**Comment by Norgus** [comment]
Created a branch for dealing with this and already completed the first few days. It'll get merged back in once I finish all of the scripts.
