### ISSUE TITLE
Censorship flag

### ISSUE THREAD

**Issue by orian34** [07th-mod/onikakushi#157]
https://github.com/07th-mod/onikakushi/blob/d4d5d2de5573b8887bdcf563fd1671d898c515a6/Update/onik_tips_01.txt#L133

From betting money to a simple challenge

Old lines : 
NULL, " It's impossible to challenge me by birthday!!", Line_WaitForInput);
	OutputLine(NULL, "　……何ならひと月差ごとに１００円の賭けをしてもいいぜー！」",
		   NULL, " ... I wouldn't even mind you if you bet a dollar per month!\"", Line_WaitForInput);
	OutputLineAll(NULL, "\n", Line_ContinueAfterTyping);

	DisableWindow();
	DrawBustshot( 1, "re_se_na_a1", -160, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 0, 0, 200, TRUE );

//「え＠　え？＠　なんでだろ＠　なんでだろ？！￥
	OutputLine(NULL, "「え？",
		   NULL, "\"Huh?", Line_WaitForInput);
	OutputLine(NULL, "　え？！",
		   NULL, " Huh!?", Line_WaitForInput);
	OutputLine(NULL, "　なんでだろ？",
		   NULL, " Why?", Line_WaitForInput);
	OutputLine(NULL, "　なんでだろ？！」",
		   NULL, " Why!?\"", Line_Normal);
	ClearMessage();

//　突然、賭けにされて狼狽するレナ＠
	OutputLine(NULL, "　突然、賭けにされて狼狽するレナ。",
		   NULL, "Rena panicked at suddenly being challenged to a wager.", Line_WaitForInput);
	OutputLineAll(NULL, "\n\n", Line_ContinueAfterTyping);

//　...うろたえ具合から今月の小遣いは残り少ないと断定する＠
	OutputLine(NULL, "　…うろたえ具合から今月の小遣いは残り少ないと断定する。",
		   NULL, "... Given how panicked she is, I am certain she doesn't have much allowance left this month.", Line_WaitForInput);
	OutputLineAll(NULL, "\n\n", Line_ContinueAfterTyping);

//　しかし...、たかだか誕生日程度でこうもうろたえてくれると、楽しくて仕方がないぞ￥
	OutputLine(NULL, "　しかし…、たかだか誕生日程度でこうもうろたえてくれると、楽しくて仕方がないぞ。",
		   NULL, "It's just... Sending her into a panic about something as simple as a birthday is so fun, I can't help myself.", Line_Normal);
	ClearMessage();

**Comment by Norgus** [comment]
To be done in https://github.com/07th-mod/onikakushi/tree/Censorship_conditionals
