### ISSUE TITLE
Higurashi Sui Textbox

### ISSUE THREAD

**Issue by seagun** [07th-mod/onikakushi#167]
I was just wondering if it would be possible to add a textbox just like the Sui one 
![screenshot_20180501-233242](https://user-images.githubusercontent.com/36550259/39494831-34e4b156-4d98-11e8-9b53-d6245ef2aeaf.png)

**Comment by enumag** [comment]
We're planning to add more textboxes in the future. I think @Petsnew was working on the code necessary to support them.

That said Sui textbox is a bit more troublesome because it's different based on if there is a name or not.

**Comment by Petsnew** [comment]
Yeah, I have a working dll here. It's not complete and does not support the sui text box yet. I'm gonna work more on it when the team finishes the higher priority stuff.
Demonstration: https://a.pomfe.co/timfen.mp4

**Comment by enumag** [comment]
Closing as duplicate of https://github.com/07th-mod/higurashi-patch-compiler/issues/35.

@Petsnew Check out that issue. That version from Inochi looks like what you need.
