### ISSUE TITLE
update scripts for our mod

### ISSUE THREAD

**Issue by Norgus** [07th-mod/onikakushi#168]
The following sections were different enough that I couldn't simply copy-paste the Japanese and English from the uncensored script in-place into our up-to-date code and so need tweaking for advmode etc.

[zonik_001_vm00_n01.txt](/07th-mod/onikakushi/blob/Censorship_conditionals/Update/zonik_001_vm00_n01.txt) - dialog000

[zomake_01_vm00_n01.txt](/07th-mod/onikakushi/blob/Censorship_conditionals/Update/zomake_01_vm00_n01.txt) - dialog004

**Comment by enumag** [comment]
Unfortunately this is not quite possible to do automatically. ADV-mode conversion mainly depends on voices so if there are no voices it doesn't really work. Also in both of these scripts a part of them already has ADV-mode and everything which would break if I tried to run it through the converter again.

**Comment by Norgus** [comment]
I was hoping someone less likely to mess it up than me could fill in the blanks by hand.

**Comment by Norgus** [comment]
I think [this commit](https://github.com/07th-mod/onikakushi/commit/b4fd5bc7873d6ba8f1e193d170b47147ac7632e6) should sort it. Not 100% sure I got it right, but I did test in both adv mode and non-adv mode.

**Comment by enumag** [comment]
Sorry I didn't have the time to look into it myself. I quickly checked your commit and it looks ok. Great work!
