### ISSUE TITLE
Some censorship conditional scripts not compiling

### ISSUE THREAD

**Issue by Norgus** [07th-mod/onikakushi#169]
On my branch "Censorship_conditionals", the following scripts won't compile and I so far cannot work out what is stopping them.
[zonik_004_vm00_n01.txt](/07th-mod/onikakushi/blob/Censorship_conditionals/Update/zonik_004_vm00_n01.txt)
[zonik_004_vm0x_n01.txt](/07th-mod/onikakushi/blob/Censorship_conditionals/Update/zonik_004_vm0x_n01.txt)
[zonik_tips_20_vm00_n01.txt](/07th-mod/onikakushi/blob/Censorship_conditionals/Update/zonik_tips_20_vm00_n01.txt)

```
Failed to compile script zonik_004_vm00_n01!

System.Exception: Line 218: Function name '<missing ID>' already previously declared.
```
```
Failed to compile script zonik_004_vm0x_n01!

System.Exception: Line 227: Function name '<missing ID>' already previously declared.
```
```
Failed to compile script zonik_tips_20_vm00_n01!

System.Exception: 26: OutputLine - Parameters were not of expected type!
```

**Comment by enumag** [comment]
Should be all fixed now.
