### ISSUE TITLE
Onikakushi is crashing at a certain point in the story

### ISSUE THREAD

**Issue by lolzzxd** [07th-mod/onikakushi#171]
In chapter 3 of Higurashi when they cry - Onikakushi (ch1) the game seemingly freezes when Rina and the main character are pulling the statue out from the dump. The music still continues playing, but I can't call the menu and the only thing it reacts to is when I try to close it. It will react with the "are you sure"? Is this because I am missing a CG or something? The previous CG's were working, but they were other art than the Updated "Updated" art (the up-to-date art), which I am using for the general sprites and that seemed a bit peculiar. Reunpacking the CG pack in the StreamingAssets folder did not work. Also I installed it with the manual downloads, instead of the installer since that got stuck many times in a row sadly. My computer is a DELL Latitude E6640 with Windows 7.
![image](https://user-images.githubusercontent.com/39388711/40205356-0cfda364-5a2c-11e8-8cc9-825e6770cd21.png)
![image](https://user-images.githubusercontent.com/39388711/40205390-2cf2f6f6-5a2c-11e8-8095-713fac531127.png)

I hope anyone will be able to help me, if you need further information about my computer feel free to ask, also I'm new to this so if it doesn't have a label, I'm extremely sorry but it was confusing.

**Comment by ItaloKnox** [comment]
I'm a little confused. The updated sprites you are currently using, are they provided by us or is it another pack from somewhere else? We made many changes to the filesystem so you might be crashing because of missing files, supposing you are not running the sprites provided by us.

**Comment by ItaloKnox** [comment]
Also, please upload the output_log file that should be inside your StreamingAssets folder. That's essential to understand the cause of this crash.

**Comment by orian34** [comment]
dialog21 is not void in the "zonik_004_vm0x_n01" file. I'll fix it to see if it fixes the error

**Comment by orian34** [comment]
There, it fixed it. It was just a redirection for the censor flag that was missing void. 

I also found a small sprite issue that I fixed aswell.

**Comment by lolzzxd** [comment]
Okay thank you very much!

**Comment by orian34** [comment]
Report any other sprites that are not the ones you are currently using if you see some, I'll fix it.

**Comment by lolzzxd** [comment]
Whatt should I redownload in order to fix the problem; the patch or the graphics patch?
