### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by seagun** [07th-mod/onikakushi#175]
So i was installing the patch on my new computer, but when i enter the game all i get is a black screen, as if it's charging all the files, but it never really starts. I tried installing the patch manually and with the installer.

**Comment by enumag** [comment]
It takes some time for the game to compile the scripts when you run the game for the first time after installing the patch (a minute maybe on slower PC). If you tried waiting and it doesn't help then post your output_log.txt file located in the `HigurashiEp0*_Data` directory.

**Comment by seagun** [comment]
Here it is.
[output_log.txt](https://github.com/07th-mod/onikakushi/files/2274418/output_log.txt)

**Comment by enumag** [comment]
Oh boy, I have no idea what these errors mean.

@ItaloKnox Have you ever seen anything like that?

Also @seagun what operating system are you using? Since you tried the installer I'd assume some version of windows, but which one?

**Comment by seagun** [comment]
I'm using windows 10

**Comment by ItaloKnox** [comment]
This is an issue with the dll. I need more information about your setup:

* 64bit or 32bit OS?
* DRM-free or Steam game?

**Comment by seagun** [comment]
64bit OS, and DRM-free for this one

**Comment by ItaloKnox** [comment]
Looks like your game is out of date. You need to grab the latest version from MangaGamer or GOG to have it working correctly.

Your game is running an older version of Unity:
``Initialize engine version: 4.6.5f1 (c2bb1d7d067c)``

Here's how it is supposed to look:
``Initialize engine version: 5.2.2f1 (3757309da7e7)``

**Comment by seagun** [comment]
Soo now it works perfectly, thanks!

**Comment by enumag** [comment]
Nice. Enjoy the game and let us know if you find anything to improve. ;-)
