### ISSUE TITLE
Alchemist BGM

### ISSUE THREAD

**Issue by seagun** [07th-mod/onikakushi#176]
Are there any plans to replace the BGM with the alchemist tracks?

**Comment by ItaloKnox** [comment]
Yes! Should be coming in the next major update for all chapters. We will start working on this very soon.

There is a beta script (hey @irlPM) that fully replaces the music, but our plan to officially support it is to make the music toggleable between PC and console. If you want to play with the console music right now, @irlPM will show you the steps.

**Comment by irlPM** [comment]
Yea I could give it to you, just tell me what chapter do you need and I can give those to you.

**Comment by seagun** [comment]
Onikakushi!

**Comment by irlPM** [comment]
I'll be giving you those when I get home in about 4 hours. Sorry for the delay!

**Comment by irlPM** [comment]
Okay,   it's basically four the soundtracks to work.
1 - Download the Soundtracks from our repo, the file is Sui-Soundtrack.zip (https://github.com/07th-mod/resources/releases/tag/Nipah)
2 - Extract those soundtracks in _HigurashiEp01_Data\StreamingAssets\BGM_
3 - Download the scripts that are attached to this comment.
4 - Extract those in _StreamingAssets\Update_
Remember that this won't work in a save file, you need to create a  new game.
[output.zip](https://github.com/07th-mod/onikakushi/files/2291971/output.zip)

**Comment by seagun** [comment]
It works, thanks! Looking forward to the full release.
