### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by mfdsrax2** [07th-mod/onikakushi#182]
The game always stops after this scene and won't go on. Everything is black, only music is looping.
![20190529223856_1](https://user-images.githubusercontent.com/13324717/58566732-b9ace600-8263-11e9-9b72-5ffd1a562279.jpg)

**Comment by ItaloKnox** [comment]
Can you please post your ``output_log`` file? It should be inside the ``HigurashiEp01_Data`` directory inside the game folder.

It is also usually called ``player.log`` if you are running Linux.

**Comment by mfdsrax2** [comment]
[output_log.txt](https://github.com/07th-mod/onikakushi/files/3237233/output_log.txt)

**Comment by ItaloKnox** [comment]
One of the game flags we added seems to not be working. Did you start a new game or is this a save from the unpatched game? That might be the cause.

**Comment by mfdsrax2** [comment]
I played the game like a year ago, using a patched version. It may be an old patch. Then I downloaded v6.0.0 and continued with the old savedata. Do I need to start the game from the very beginning in order to get the game running?

**Comment by tellowkrinkle** [comment]
You can go into the おまけ/Extras menu and there should be a chapter jump button, use that to jump to the start of the chapter your save is at (I think day 9) and then fast forward with ctrl

**Comment by enumag** [comment]
Yeah it's a known issue that save files from previous versions of the patch don't always work. Try to do what tellow said and open a new issue if the problem persists.
