### ISSUE TITLE
Censorship state

### ISSUE THREAD

**Issue by hahio** [07th-mod/onikakushi#186]
Hi,

Is there a way to know which censorship level we are currently playing with?
I don't mind if it's an in game method or to check a binary save file (as long as I know what to look at).

By the way, you have done an awesome job creating this mod.

**Comment by enumag** [comment]
Press F10 while in the story mode. Look for voice matching level.

**Comment by hahio** [comment]
Thank you for your rapid answer. 
Unfortunately, I don't have access to the F10 menu.
( just in case, I am running kubuntu 18.04.2. and my F10 key is working properly).

**Comment by enumag** [comment]
**while in the story mode**

**Comment by enumag** [comment]
As in it won't work in main menu, config screen etc. Only when there is actual text and character sprites on the screen.

**Comment by hahio** [comment]
I am such an idiot ... , this ticket betrayed me [https://github.com/07th-mod/onikakushi/issues/104](url)
Sorry for wasting your time, but maybe it will help other users (cheering myself how I can)
