### ISSUE TITLE
Feature: enable the 2020 demo BGM?

### ISSUE THREAD

**Issue by webbedspace** [07th-mod/onikakushi#203]
https://twitter.com/07th_official/status/1283234839336873984

This is an official demo of Higurashi, containing both Onikakushi and Watanagashi, released in June 2020. Most notably, it uses a different method of substituting the copyright-struck AIDIA tracks than the April 2019 update.

This features the following never-before-seen tracks by xaki:

* delayeDstepS (2:56)
* ＭＩＮＤ　ＴＨＥ　ＧＡＰ(1:57)
* ReversibleEmotion (2:34)
* Tの符号 (2:40)
* さよならの空気の中で (4:29)
* スクールモードでいこう (1:56)
* ルリグ・トラムス (3:16)
* 優しさの白い風 (1:48)
* 巫 (1;57)
* 目覚めは穏やかに (2:02)
* 覡 (2:41)

Most of these tracks later appeared on [this June 2021 OST](https://vgmdb.net/album/112209).

Rather than doubling up various Answer Arc tracks, the demo uses the following substitutions (along with the four U2 Akiyama tracks from the April 2019 update):

| AIDIA | xaki or U2 |
| --- | --- |
| Silver Mirror | delayeDstepS |
| 洞窟 [Cave] | Tの符号 |
| 魔族研究所 [Demonic Institute] | ＭＩＮＤ　ＴＨＥ　ＧＡＰ |
| Spring Step | ReversibleEmotion |
| Lunch Time | 優しさの白い風 |
| Silence | 目覚めは穏やかに |
| Small Town | ルリグ・トラムス |
| 静寂 [Quietness] | 巫 | 
| パリの午後 [Afternoon in Paris] | スクールモードでいこう |
| オレンジ色の詩 [Orange-colored Time] | さよならの空気の中で | 
| 朝露 [Morning Fog] | 覡 |
| Baby's Walk | Nipa~☆ |
| Hello! | Kneecap |
| スタコラサッサ [Helter Skelter] | Bright Sun |
| Digital Network | Spinning Seesaw |

Even though the demo does not contain Tatarigoroshi or Himatsubushi, the same substitution table above could be applied to them, too, since they don't add any additional AIDIA tracks.

I did NOT research the sound effects used in the demo.

I think it would be great to offer this as an alternative to the "OG BGM" mod, for the following reasons:

* Xaki did a good job of imitating the removed AIDIA tracks stylistically - just listen to "ＭＩＮＤ　ＴＨＥ　ＧＡＰ" and you can instantly tell that it's a "Demonic Institute" replacement.
* Moreover, most of the tracks loop much later than the AIDIA tracks. "Silver Mirror" is a 30 second loop that isn't even very clean, whereas "delayeDstepS" takes the mood and general instrumentation of it and develops it over a longer time.
* When I researched this, I was baffled to find that the Mangagamer versions of Onikakushi was never updated at the same time to use these tracks. These feel like the "true" replacements for the AIDIA tracks, which the April 2019 update was merely a legally-required emergency patch for.
* The fact that these are official 07th Expansion tracks makes them much more legitimate than, for instance, the early 2010's Mangagamer soundtrack.
* Moreover, it seems likely that future Higurashi releases on other platforms could use these tracks, and that these should be considered part of Higurashi's history from now on.

The fact that the substitutions are so simple makes me think this should be relatively easy to implement.

**Comment by drojf** [comment]
Sorry for the late reply, I wanted to ask the team on discord what they thought of this before writing anything, in case they hadn't seen this yet.

It's my understanding that this is the Hou+ demo (keep in mind I've not really been keeping up with Higurashi stuff). We've had some requests already to include the improved OG sprites from the Hou+ demo, and told them to wait for the full release before taking any action, in case there are changes or more sprites added in the full release. Likewise I would want to wait for the full release before trying to incorporate the BGM from Hou+ (assuming it's happening some time soon).

So in summary, we'll probably wait until Hou+ fully releases before working on this. 

For now, could you add the filename in the demo (for each xaki or U2 BGM) to each row in your table above (like `5.ogg`)? I downloaded the demo and am not sure which file corresponds to which song.

----

Here is a comment from steam by "cheironyx:" I'm going to record if/when we decide to work on this, so I know the mapping of song name -> mangagamer filenames

> Originally posted by cheironyx:
> I haven't checked absolutely everything, but as far as I'm aware, this is a complete list of the music replacements:
> 
> msys01: Pari no Gogo -> Fuushagoya no Shounen (from Meakashi-hen)
> msys02: Hello! -> Kneecap (from Hirukowashi-hen/Daybreak OST)
> msys03: Sutakorasassa -> Bright Sun (from Hirukowashi-hen/Daybreak OST)
> msys04: Digital Network -> Spinning Seesaw (from Daybreak OST)
> msys05: Orenji-iro no Toki -> What is wished (from Meakashi-hen)
> msys06: Silence -> Iru (from Meakashi-hen)
> msys07: Doukutsu -> Kyouki e no Kairou (from Meakashi-hen)
> msys08: Mazoku Kenkyuusho -> Kyouki (from Meakashi-hen)
> msys09: Seijaku -> Near sightedness to parallel -taidou- (from Minagoroshi-hen)
> msys14: Asagiri -> new
> msys15: Silver Mirror -> new
> msysmi: Spring Step -> new
> msysre: Lunch Time -> new
> msysri: Baby's Walk -> Nipa~ (from Hirukowashi-hen/Daybreak OST)
> msyssa: Small Town -> new
> lsys28: Loop131 -> new
> 
> It looks to me like Ryukishi07 ran into some sort of copyright issue with AIDIA, since their songs are the only ones that got replaced outright. Not only are the AIDIA songs missing from all the console ports (even Entergram's Hou, which reintroduced some of the other non-Higurashi-specific tracks like Dancers7 and Z-E-R-O), they were even removed from the (Japanese) free trial version of Onikakushi-hen way back in mid-2006.
> 
> In fact, most of the 2019 changes are the same as the changes in the 2006 trial version, with the only obvious differences being the brand new tracks. For those curious, the trial replaced Lunch Time and Small Town with Fuushagoya no Shounen (although the game files still included the original MP3s for these two), Silver Mirror with Soak (from Meakashi-hen) and Asagiri with cicada sound effects (Semi.wav), and left out Spring Step and Loop131 entirely (since they aren't used in Onikakushi-hen). Also, the four songs I listed as "Daybreak OST" above were actually created specifically for this trial version, so I'm glad that they reused them elsewhere and gave more people a chance to hear them.
> 
> Oh, and if anyone figures out any details about the six new tracks (who made them, what they're called, etc), let me know!

**Comment by webbedspace** [comment]
| File | Track |
| --- | --- |
| 1.ogg | スクールモードでいこう |
| 2.ogg | Kneecap (but with different mixing) |
| 3.ogg | Bright Sun |
| 4.ogg | Spinning Seesaw |
| 5.ogg | さよならの空気の中で |
| 6.ogg | 目覚めは穏やかに |
| 7.ogg | Tの符号 |
| 8.ogg | ＭＩＮＤ　ＴＨＥ　ＧＡＰ |
| .ogg | 巫 |
| Tip.wav | 覡  |
| mion.ogg | ReversibleEmotion |
| rena.ogg | 優しさの白い風 |
| satoko.ogg | ルリグ・トラムス |
| rika.ogg | Nipa~☆ |
| GIWAKU2.ogg | delayeDstepS |

**Comment by webbedspace** [comment]
I believe Hou+ is out now, right? Any interest in this?

**Comment by drojf** [comment]
Are there any changes to the OST as compared to the demo, or is it the same as before?

We are busy now because we're working on Higurashi Rei, but once my part is done I can probably look at it

**Comment by webbedspace** [comment]
Well, uh… I was going to purchase it to find out, but apparently it's only sold physical media only… which is a bit of a problem for me personally… so I'll get back to you on that.

I'm sure you've noticed now that one of the tracks (スクールモードでいこう) appears in (MangaGamer) Rei's cast review.

**Comment by drojf** [comment]
I just went through the BGMs. I feel silly now because I didn't realize the filenames were so similar for most of them, so I was putting it off until now.

Hou+ BGM Track Name | Hou+ Filename | Mangagamer Track Name | Mangagamer Filename
-- | -- | -- | --
スクールモードでいこう | 1.ogg | パリの午後 (Pari no Gogo) [Afternoon in Paris] | msys01.ogg
Kneecap (but with different mixing to the Mangagamer ver) | 2.ogg | Hello! | msys02.ogg
Bright Sun | 3.ogg | スタコラサッサ [Helter Skelter] OR Bright Sun? | msys03.ogg
Spinning Seesaw | 4.ogg | Digital Network | msys04.ogg
さよならの空気の中で | 5.ogg | オレンジ色の詩 (Orenji-iro no Toki) [Orange-colored Time] | msys05.ogg
目覚めは穏やかに | 6.ogg | Silence | msys06.ogg
Tの符号 | 7.ogg | 洞窟 (Doukutsu) [Cave] | msys07.ogg
ＭＩＮＤ ＴＨＥ ＧＡＰ | 8.ogg | 魔族研究所 (Mazoku Kenkyuusho) [Demonic Institute] | msys08.ogg
巫 | 9.ogg | 静寂 (Seijaku) [Quietness] | msys09.ogg
覡 | Tip.wav | 朝露 (Asagiri) [Morning Fog] | msys14.ogg
ReversibleEmotion | mion.ogg | Spring Step | msysmi.ogg
優しさの白い風 | rena.ogg | Lunch Time | msysre.ogg
ルリグ・トラムス | satoko.ogg | Small Town | msyssa.ogg
Nipa~☆ | rika.ogg | Baby's Walk | msysri.ogg
delayeDstepS | GIWAKU2.ogg | Silver Mirror | msys15.ogg

If there are any changes in the full Hou+ release let me know, otherwise I'll create a new BGM pack by just renaming the bgm files to match the Mangagamer filenames (looks like I'll need to convert `Tip.wav` from WAV -> OGG too).

You can do this too if you feel like doing it, just let me know.


-----

> I'm sure you've noticed now that one of the tracks (スクールモードでいこう) appears in (MangaGamer) Rei's cast review.

Don't tell anyone but I actually haven't played the Higurashi VNs besides testing various features of the mod...

**Comment by enumag** [comment]
> Don't tell anyone but I actually haven't played the Higurashi VNs besides testing various features of the mod...

@drojf Welcome to the club. :-D I only played the question arcs. Never played either answer or console arcs haha. I just like the atmosphere and teamwork around here. ;-)

**Comment by drojf** [comment]
It appears that some time ago, Kilicool64 on our discord has created a pack which is the above. Reading their comment, it seems to agree with what I worked out in the table earlier.

Here's what they wrote on discord

> In case anyone's interested, this patch can make the question arcs use the new non-MIDI tracks from Hou+'s demo. I just skipped through all four of them and noticed no issues.
> 
> If you extract them into the BGM directory, they'll play when you use the new OST. They should also work with the old OST option if you put them in OGBGM instead, but I haven't tested that. It would barely make a difference. I believe that aside from the non-MIDI tracks, only one track is different in both OST versions 07th Mod offers.
> 
> For the most part, all I had to do to make it work was rename the tracks. The only exception is the TIPS music. For some reason, this track is a WAV file, so I had to convert it to OGG first. I picked the highest possible bitrate, so the compression shouldn't be very harsh.
> 
> https://www.mediafire.com/file/5lqogeta2phscil/Hou++demo+track+patch.7z/file
> 

 I haven't contacted them yet about this but we should be able to use this when we implement this feature.

**Comment by drojf** [comment]
The Hou+ Demo BGM has now been added to the game as a BGM option, so closing this issue.
