### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Kilicool64** [07th-mod/onikakushi#208]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/10e62e47-7488-4f32-872b-9217b6f3e2ee)
Will post updates if I find more.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/38fb9311-51ec-417f-a266-d26d5646f6d2)
Same issue. May have been a copy-paste mistake. Did this say something other than axe in the past?

**Comment by Kilicool64** [comment]
Happened again a few lines later. Not gonna bother to keep taking screenshots of this. Just do a find+replace for "a axe".

**Comment by orian34** [comment]
I can't find "a axe" when searching the repo.

**Comment by drojf** [comment]
zonik_004_vm00_n01.txt

it's in this file, depending on the voice matching level, I'll get proper link in a sec

```
	if(GetGlobalFlag(GCensor) >= 2){ModCallScriptSection("zonik_004_vm0x_n01","dialog009");}
	if(GetGlobalFlag(GCensor) <= 1){ModCallScriptSection("zonik_004_vm00_n01","dialog009");}
```

**Comment by drojf** [comment]
Should be just these four instances in that file.

https://github.com/07th-mod/onikakushi/blob/24c8f58dcfe09a77bdc7630448e81ca0ae579b5c/Update/zonik_004_vm00_n01.txt#L256

https://github.com/07th-mod/onikakushi/blob/24c8f58dcfe09a77bdc7630448e81ca0ae579b5c/Update/zonik_004_vm00_n01.txt#L265

https://github.com/07th-mod/onikakushi/blob/24c8f58dcfe09a77bdc7630448e81ca0ae579b5c/Update/zonik_004_vm00_n01.txt#L285

https://github.com/07th-mod/onikakushi/blob/24c8f58dcfe09a77bdc7630448e81ca0ae579b5c/Update/zonik_004_vm00_n01.txt#L298

I think you only ever see this if your voice matching level is 0 or 1. (closer to PC)

**Comment by Kilicool64** [comment]
Yeah, my voice matching level is at 0.
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/1ceecce8-2c7f-4940-bbd3-358c070ada95)

**Comment by Kilicool64** [comment]
Rena's "hauuu" seems to be translated differently on some occasions. In particular, I've seen her say "hao" multiple times.

This arc's translation is also guilty of frequently having characters, especially Rena, refer to people they're directly talking to in third person in situations where it's not appropriate in English.

Also, some of the references to money are converted from Yen to Dollars, but not all of them.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/ff6dc66b-593a-4241-9621-c9924a58b923)
Elongating the e at the end doesn't really make sense, given that it's silent.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/d8d2f1b2-cece-4b6d-8f29-087b9ef6cc97)
Does it really make sense for Rika to use "we" here? She should just be confirming that she already found what she needs, then ask Keiichi if it's the same for him. So shouldn't it be "I"?

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/f34ecbb4-2a5c-464e-a22f-32f2faf2e0bb)

**Comment by orian34** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/53983097/318230567-f34ecbb4-2a5c-464e-a22f-32f2faf2e0bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4Mzg1MzAsIm5iZiI6MTcxMTgzODIzMCwicGF0aCI6Ii81Mzk4MzA5Ny8zMTgyMzA1NjctZjM0ZWNiYjQtMmE1Yy00NjRlLWEyMmYtMzJmMmZhZjJlMGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDIyMzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NGE5MTlkZWQ4NDUwZThlOTA2M2E4MmUzZGQ4ZDc5ODNmOTMzOTFlMzMzY2FlNTA2OTBhMzlmYTlkMjMwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QkYsHql53Ua84bfciQZxkH3eKR8d_TOSLFgEbtTioyc)

Where is the problem on this one?

**Comment by Kilicool64** [comment]
> > ![grafik](https://private-user-images.githubusercontent.com/53983097/318230567-f34ecbb4-2a5c-464e-a22f-32f2faf2e0bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4Mzg1MzAsIm5iZiI6MTcxMTgzODIzMCwicGF0aCI6Ii81Mzk4MzA5Ny8zMTgyMzA1NjctZjM0ZWNiYjQtMmE1Yy00NjRlLWEyMmYtMzJmMmZhZjJlMGJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDIyMzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NGE5MTlkZWQ4NDUwZThlOTA2M2E4MmUzZGQ4ZDc5ODNmOTMzOTFlMzMzY2FlNTA2OTBhMzlmYTlkMjMwZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QkYsHql53Ua84bfciQZxkH3eKR8d_TOSLFgEbtTioyc)
> 
> Where is the problem on this one?

That link doesn't work for me. Can't see the image.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/79dc32a3-13d1-4df9-a3e2-e93a24796734)
Here's an especially weird use of Hao.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/1ac7ad8e-b818-4ef3-b592-5c984bbc6227)
Quadruple period.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/39c6ceab-3754-4592-972d-4cc39141dc7a)
For some reason, part of the first TIP's name has a notably thinner font than everything else.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/26fcc008-23c3-4fc8-9e55-a8010fe1aa00)
Missing word.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/28443195-3492-4ad8-a044-8c7d626bc07e)
Double period.

**Comment by orian34** [comment]
> For some reason, part of the first TIP's name has a notably thinner font than everything else.
> 
> Also, is Satoko's last name really romanized like this in the translation? I thought it was always spelled Houjou.
> 
> Edit: Yeah, this is clearly a mistake. Even the actual TIPS selection menu spells it Houjou. How did that happen?

Make sure to not mix issues that aren't script typos. That one needs image editing.

**Comment by orian34** [comment]
That one is correct. "one of those shows you love so much" can be "it" and you see it easily: Was it on last night?

**Comment by Kilicool64** [comment]
> That one is correct. "one of those shows you love so much" can be "it" and you see it easily: Was it on last night?

Whoops. Yeah, I see it now. Didn't read the sentence properly.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/acaccd5b-82dd-4bab-9c44-834577fae1fb)
Weird to see Rena refer to herself in third person here. Most instances of that were removed in the translation. Probably won't be mentioning future instances of this, but I recall her way of speaking generally being inconsistent.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/515fc741-5fd4-4535-86cb-8e0a8b69d59a)
Are there any parts in other arcs that bring up manga? Might be worth checking for consistency if it always gets translated as comics.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/382fb2e4-b0a3-475e-af3e-0a652eb82b05)
I don't think double question marks are a common sight in English. I ignored an earlier instance because it was for a rather strong exclamation of surprise, but are they really appropriate here?

**Comment by orian34** [comment]
"quit their job" No, it's correct in context. They is the subject mentioned.
For the double question marks, I found 37 results for that, so it's same to assume it's used frequently. Doesn't matter much, it makes emphasis.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/2c470970-5246-4f9e-a09a-875200c1503a)
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/dd95a87f-bed6-462f-88be-c28286136a08)
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/3bb0116d-d668-4c60-8e07-657c484f98c9)
Only found this afterwards in the fourth, 9th and 10th TIPS, but this capitalization is inconsistent with the rest of Onikakushi's translation, which uses "pm" rather than "PM."

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/29a17bdf-7952-444c-befa-1a6ec2aa10ad)
Considering PM is never written like this in Onikakushi outside of the TIPS, I'd assume AM isn't meant to be handled like this either.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/b1ce8083-3cfb-4cb0-812d-d4825bf9de9c)
That last sentence seems weird to me. Maybe remove the "to?"

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/a60cd071-df34-466b-a17e-169998ad6c31)
Sudden shift in tense.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/c86b57f3-554f-4b57-a6b6-e353b9b992ac)
Shouldn't it be "woken?"

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/a2ff1871-c753-4258-9df1-15ade6203706)
I assume it should either be "enemy was" or "enemies were."

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/c4d58a90-8ab2-4e8f-ad29-a5269d8e9342)
The last two paragraphs are both spoken by Mion, yet are separated with quotation marks. That seems weird and doesn't normally happen in Higurashi's script from my experience. Might be because the second paragraph is from a censorship-level dependent script. If these two blocks of text aren't separated like this in the original script, I don't think they should be here, but I don't know if they are.

**Comment by Kilicool64** [comment]
Was that line in the original PC version? If so, why is retaining it not an option, even when the voice matching level is set to 0?

**Comment by Kilicool64** [comment]
Ah, okay. So Rena used to speak it herself. In that case, you should eliminate the quotation marks separating it and the previous line, since no change in speaker is happening anymore.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/8bdcd6a4-7af5-421d-93f3-cf7c0a2dc8c6)
Seems weird that the single quotation marks don't surround the "out" in the last line, given that they do in the other three instances. Is that how it's supposed to be?

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/78590711-18ea-4b24-8a74-3a51af1e6332)
I don't think the translation usually puts a space after an opening ellipsis. Might be wrong, though.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/642e2ed1-dc82-4d35-9cc9-96e6001500d6)
More third person use.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/227a50b2-e0c2-4456-9263-d2abcea677c9)
For some reason, Rena refers to Keiichi without honorific here, even though she clearly does in Japanese. This is ignoring the whole awkwardness of her using third person here to begin with.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/9b05ac9a-8494-44ad-ae9b-4cc692e11cce)
Tense shift.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/9b55d12e-8ffc-4943-bf1e-6f97ece21a5a)
Another one, though a bit more debatable.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/e9e5f99f-a23f-4a9d-a3a0-bd9507d2ce3b)
Doesn't seem like a question to me.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/3d3ee160-91e4-4e37-9f65-4e7bb90c061a)
Missing space.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/bf25ebe5-a07e-4e7b-93ad-781251811474)

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/f66dff2d-58b7-4dc0-905c-3217fb9d1e2f)
Again, that doesn't look like a question to me.

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/eb71fd8a-262e-4d81-8492-72b73a0531b7)

**Comment by Kilicool64** [comment]
![grafik](https://github.com/07th-mod/onikakushi/assets/53983097/8befc3d5-b137-44e0-b3a2-d8a4abf40160)
Unwanted space.

**Comment by Kilicool64** [comment]
Okay, I'm done. Moving on to Watanagashi next.

**Comment by orian34** [comment]
Thanks, fixed that stuff. Btw you missed a handful more of those 'transfer' out

**Comment by Kilicool64** [comment]
I see you changed one of the lines to "Then Keiichi-kun picked out that big box of Pork-bone & Ginger flavor that you love so much, didn't you☆?"

Does that really make sense? It still refers to Keiichi in third person at first, then switches to second person. Wouldn't it be better to use second person everywhere?

Also worth noting that there are loads of lines line this throughout Onikakushi. (And at least a few more instances of Rena using third person on herself.) If you're on board with them being changed, I can start pointing them out as well from now on.

**Comment by orian34** [comment]
I guess so yeah.
