### ISSUE TITLE
Issue with "furry little seal" line with slow text speed

### ISSUE THREAD

**Issue by Kilicool64** [07th-mod/onikakushi#209]
It seems the engine is instructed to advance automatically at this line after a certain amount of time. However, it was presumably timed with the default text speed in mind. Mine is slower, so the line never gets fully displayed for me.

Is there some way to make the engine only start the timer after the line is fully displayed? That would be a far better solution than this, assuming I understand how it works correctly.

**Comment by orian34** [comment]
There's no perfect solution, but I made the line need to be finished before it goes after, and reduced the wait time accordingly.
