### ISSUE TITLE
Missing voice file

### ISSUE THREAD

**Issue by enumag** [07th-mod/onikakushi#29]
This [voice file](https://github.com/higurashi-mod/onikakushi/blob/b1afb0af811ae971ab85527dc26db66a6eb23ad0/Update/onik_015.txt#L1352) does not exist in the voices patch.

**Comment by ItaloKnox** [comment]
That's because that line doesn't exist in the PS3 script. Someone went there and added the path.

> S01/01/120100654	「魅音に直に、ダム現場で事件がなかったかって聞いたよな。
> S01/01/120100655	…魅音はないって言ったじゃないか！！！
> S01/01/120100657	　嘘つき野郎ッ！！！」``

``//「魅音に直に、ダム現場で事件がなかったかって聞いたよな＠...魅音はないって言ったじゃないか！！＠　バラバラ殺人があったのによ！！＠　嘘つき野郎ッ！！！＠
	PlaySE(3, "s01/01/120100654", 256, 64);
	OutputLine(NULL, "「魅音に直に、ダム現場で事件がなかったかって聞いたよな。",
		   NULL, "\"Mion, I asked you directly if something happened at the dam, didn't I?", Line_WaitForInput);
	PlaySE(3, "s01/01/120100655", 256, 64);
	OutputLine(NULL, "…魅音はないって言ったじゃないか！！！",
		   NULL, " ...And you told me nothing happened!!", Line_WaitForInput);
	PlaySE(3, "s01/01/120100656", 256, 64);	
	OutputLine(NULL, "　バラバラ殺人があったのによ！！！",  // this line here
		   NULL, " When someone was dismembered and murdered!!", Line_WaitForInput);
	PlaySE(3, "s01/01/120100657", 256, 64);
	OutputLine(NULL, "　嘘つき野郎ッ！！！」",
		   NULL, " You lied to me!!!\"", Line_WaitForInput);
	OutputLineAll(NULL, "\n", Line_ContinueAfterTyping);``

I'll leave it like this for now, maybe we can find it in the PS2 voices.

**Comment by enumag** [comment]
@ItaloKnox Formatting markdown is easy. Empty line, three backticks on a line by themselves, code, three backticks on a line by themselves, empty line.
