### ISSUE TITLE
Blurry sprites?

### ISSUE THREAD

**Issue by LoLyeah** [07th-mod/onikakushi#32]
After applying the patch, I got blurry sprites.
Here is my screenshot.
(Standard Resolution)
http://i.imgur.com/dG8NpLR.jpg
http://i.imgur.com/vCJMc1C.jpg
(800x600 Resolution)
http://i.imgur.com/S0R485R.jpg

No, if you said the downloaded patch was corrupted, look here.
http://i.imgur.com/mE54aCg.jpg

I'm using "Higurashi Steam - Tweaked Steam sprites + PS3 assets Mod 1.5 [Wide screen support]" version.

**Comment by ItaloKnox** [comment]
Oh crap, Github didn't email me this. Are you still having trouble?
Development is pretty much done and no updates have been released since them (both game and patch).

I didn't work in the graphics patch, but you should try to run the game in widescreen. Maybe if the generals are still happening on /jp/, someone might be able to help you there.

**Comment by LoLyeah** [comment]
![screenshot_268](https://cloud.githubusercontent.com/assets/11774211/9085109/20e493aa-3ba4-11e5-9176-779c2c90e51e.jpg)

Well, how to run it in widescreen? Sorry for bothering you :>

**Comment by ItaloKnox** [comment]
Download the [master file](https://github.com/higurashi-mod/onikakushi/archive/master.zip), repeat the installation process described in the first page, except this time you only need the Update folder.
After that go to "\SteamApps\common\Higurashi When They Cry\HigurashiEp01_Data\StreamingAssets\CompiledScripts" and delete everything inside this folder. 

That will force the game to reload the scripts, it should open in full screen automatically after that. Don't worry if the game hangs for a while after you do this, just let it open for some seconds and it will recompile the scripts and work.

**Comment by LoLyeah** [comment]
![screenshot_276](https://cloud.githubusercontent.com/assets/11774211/9153545/e61e4afe-3e87-11e5-86d9-112a6748976e.jpg)
![screenshot_277](https://cloud.githubusercontent.com/assets/11774211/9153547/19a934d8-3e88-11e5-9070-611c062e9f48.jpg)

The widescreen feature is working, but yeah, it's still blurry.
FYI, the original CG isn't blurry though.
![screenshot_278](https://cloud.githubusercontent.com/assets/11774211/9153550/463a2b4c-3e88-11e5-9cfe-db81cbbb8b65.jpg)

I'll try downloading the non-widescreen version and see if the problem is stills there or not.

**Comment by ItaloKnox** [comment]
That's odd. Can you reinstall the graphics patch?
I know the files look fine when you browse them through your PC, but try installing the graphics patch again if you haven't done it before. The game engine just puts the images in, there is nothing there to change the look of their behaviour (other than effecs, but only transitions).
