### ISSUE TITLE
CGs Not Working :(

### ISSUE THREAD

**Issue by konartist96** [07th-mod/onikakushi#67]
OK so i don't know why but the cgs are not working for me, when i look at the CGAlt folder they are there but they don't show up in game. Any Solution??? :(

**Comment by ItaloKnox** [comment]
Try cleaning both CompiledScripts folders and running the game again. It should hang for a few seconds and then boot normally after that.

**Comment by konartist96** [comment]
what do you mean by "both CompiledScripts folders" I only see one???

**Comment by ItaloKnox** [comment]
If you are running the most recent version of the game, you should have a folder called CompiledScripts and CompiledScriptsUpdate. You are supposed to clean both.

If you are running an older version of the game, the patch is not properly supported until the first update.
