### ISSUE TITLE
PS3 Video Opening

### ISSUE THREAD

**Issue by Palcto** [07th-mod/onikakushi#68]
Just wondering, would it be possible to mod in some of the PS3's intros into this engine? 

It'd be pretty cool if some of the Sui's op started playing like https://www.youtube.com/watch?v=mVLKN7Q8iA0 or https://www.youtube.com/watch?v=iyYMHRga2bc

**Comment by ItaloKnox** [comment]
I think it's possible, but definitely not a priority right now. I'll leave this open for when our work tone down a bit.

**Comment by Palcto** [comment]
Will this still be done? Is there any way we could do it ourselves?

**Comment by ItaloKnox** [comment]
Completely missed this, sorry about that. I'm not sure if the engine currently supports videos, since we have to yet see it running one. I'll try to pitch this to the team so we can see what can be done.

**Comment by enumag** [comment]
@P-Chang While going through the engine source code, did you see anything that could mean some support for videos? Do you think this is doable some time in the future?

**Comment by P-Chang** [comment]
@enumag 
I know Unity support video, but there are no command like `PlayVideo` in AssemblyCSharp.dll.
If I find the way to play video, I'll test it.

**Comment by irlPM** [comment]
Movie support for onikakushi is released, closing this issue.
