### ISSUE TITLE
Blurry BG

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/onikakushi#72]
I just went though some random ones and found a few. 

bg_010
bg_117
aka1
bg_074
bg_075

**Comment by ItaloKnox** [comment]
I guess that's for you, @Grelo. Not really easy to me to fix since I don't have the proper images to update.

**Comment by Kamlingen** [comment]
Nearly all of them had the blurriness so I just replaced them all.

Link up soon

I removed 3 files from the original patch.
mangagamer - copie
haikei-
07thlogo - copie

**Comment by ItaloKnox** [comment]
Nice. I think I got a solution for updating the patches easily, so it looks like a good time to see if it works well.

**Comment by Kamlingen** [comment]
So what I did was replacing all the BG in Onikakushi with the corresponding ones in Watanagashi. So I couldn't do anything with the CG except 07.

**Comment by enumag** [comment]
@ItaloKnox @Grelo I'm not sure I understand this issue. What do we need to do here?

**Comment by ItaloKnox** [comment]
I think nothing, this is an old issue OP didn't close and neither did I. Seems to be fixed. 👍
