### ISSUE TITLE
Version from the mangagamer site

### ISSUE THREAD

**Issue by gaspardenuit** [07th-mod/onikakushi#73]
Hi! 
I am not sure if this is the correct place to ask but just wanted to know if the patch will work properly if I use it on the version that you can buy directly from the MangaGamer site instead of the one on Steam. I ask this because for the other question arcs it says in your installation guides that you can use either version but in the Onikakushi one it only says Steam.

**Comment by ItaloKnox** [comment]
Yes, it should work fine on both versions as long as they are updated. Grabbing the game from MangaGamer's store should be already the latest version, so you're fine.

**Comment by gaspardenuit** [comment]
Thanks! I just realized I missed the "closed issues" tab (I'm new to github) where there were a bunch of topics and one of them asked a similar question, sorry!

The patch worked fine but not right away, at first there was just a black screen. The output log file said that it "Could not CallScript flow, as the file was not found" so I copied the "flow.txt" from the Scripts folder to the Update one and it worked perfectly! 
I think the problem was that I erased everything from the CompiledScripts folder beforehand (since I ran the game before applying the patch and didn't want it to read the old files).

So yeah I can confirm that it works perfectly with the version bought directly from the MangaGamer site.

**Comment by ItaloKnox** [comment]
No worries, we're always glad to help.

And that's right, the scripts are supposed to go inside the Update folder and cleaning both CompiledScripts folders (or at least one of them) will make the game hang in a black screen for a few seconds while it recompile the files.

If you find anything wrong or need help setting up anything, just create another issue and I'll do my best to solve it. Enjoy the patch! 😄
