### ISSUE TITLE
CG not used

### ISSUE THREAD

**Issue by Grelo** [07th-mod/onikakushi#75]
I found CG not in use so i added it to script but dont know how to upload only the difference so here you go.

[onik_014_02.txt](https://github.com/07th-mod/onikakushi/files/965107/onik_014_02.txt)

**Comment by enumag** [comment]
Your file is a bit outdated as it doesn't contain my changes from [this commit](https://github.com/07th-mod/onikakushi/commit/c286b2ca164b54c84d3a3e67fd601185afd1618a) so I can't merge it easily with just GitHub edit. I'll try later locally.

**Comment by enumag** [comment]
@Grelo All done, thank you!
