### ISSUE TITLE
Unnecessary files

### ISSUE THREAD

**Issue by Grelo** [07th-mod/onikakushi#76]
Do you guys know if the pics with MG rena in forest in PS3 files are in use? I can recreate them if they are. Same problem is in Watanagashi with Mion. Thanks.

**Comment by ItaloKnox** [comment]
Can you be more specific? I don't remember much of Onikakushi but maybe I can help.

**Comment by Grelo** [comment]
Files like these. Example:

![oni_re_01](https://cloud.githubusercontent.com/assets/22790067/25696239/b5a06718-30b6-11e7-8f4d-77d2d5968650.png)
![oni_re_05](https://cloud.githubusercontent.com/assets/22790067/25696238/b59f902c-30b6-11e7-8e73-70122903746d.png)

**Comment by ItaloKnox** [comment]
Oh, I also found those when I was looking the patch files and wondered the same. Maybe @enumag can help?

**Comment by enumag** [comment]
Of course. I wanted to look into unused CGs and backgrounds anyway.

**Comment by enumag** [comment]
@Grelo As I thought these files are not used. They are from the original MG game files. Our installer only adds and replaces files but does not remove any existing files even if they're no longer needed. On the other hand we can't just delete all the original files before applying the patch beacause files like onik001.png are still used. However you said you'll replace such files with 16:9 variants later, right? When that's done we might be able to remove all MG files before applying the patch. Anyway I'll deal with this when I improve the compiler to remove all duplicates.

**Comment by Grelo** [comment]
@enumag They are from Guras mod, i still have them in mod before merge with MG CG folder. Their MG counterparts in vanilla folder are there looking the same just with ugly sprites, so im surprised they are not used when original folder have them...
And the notes and end scenarios yes ill create them, but i thought these would be the priorities.

**Comment by enumag** [comment]
@Grelo Interesting. Well they're commented out in our scripts. Besides we don't want to use files that don't match the PS3 graphics. Btw. I made some progress with the script to find the duplicates. It will take time but should be doable.

In my opinion removing useless files is not much of a priority - they just eat some disk space but otherwise don't matter at all - nobody will see them. Scenarios screens on the other hand are a visible improvement and I'm looking forward to them. No need to rush things though. Most people interested in Higurashi already read the question arcs anyway.

**Comment by enumag** [comment]
@Grelo @ItaloKnox @DoctorDiablo Ok so I have an experimental version of the compiler which detects unused images in CG and CGAlt directories. And here is the thing - it found over 300 unused images in our Onikakushi graphics patch alone, Is that even possible? I randomly checked some of them but it all seems real. Most of it are the weather sprites - it looks like whey were made by a batch with no regard to which are actually needed. I can't remember who made them though.

**Comment by Grelo** [comment]
I dont know. Onikakushi and Watanagashi weather sprites etc. made Gura so its possible. But better check that before you delete anything :D

**Comment by DoctorDiablo** [comment]
I'd believe it.  It's probably safe to delete them, but we would have to verify.

**Comment by enumag** [comment]
Well my compiler already has missing files detection feature. When I remove all of these files it doen't report any missing files so it is fine.

There are some files that the game actually uses without mentioning them in the scripts. I don't know which files are used this way though. To be safe I decided to only remove files that I can identify as sprites or bgs.

**Comment by DoctorDiablo** [comment]
I know the _j files are used even though the script doesn't explicitly reference them.  The engine is smart enough to append _j to the file name if the language is set to Japanese.

**Comment by ItaloKnox** [comment]
300 unused images sound a bit too much but I still have the feeling that it's not a mistake. It should be dangerous to update the patch to remove them and then we get flooded with issues because of that. We should make sure we're not removing something important that is in the middle of that.

**Comment by enumag** [comment]
Yeah I know that as well. Then there is windo_filter.png which is always used. And a bunch that I do not know whether they are used or not but assume they are like x.png, white.png, 2.png, 4.png, 5.png, left.png etc.

**Comment by enumag** [comment]
@ItaloKnox I spent several hours on it today. When I reduced it to just sprites and bgs while carefully not touching the Frederica note which is named as a sprite it went down to around 250 (500 with CGAlt). I also updated the script to print out which images it removed so that we can manually verify that it did not remove anything it should not have. As far as I can tell everything seems ok for Onikakushi. I'm testing Watanagashi now.

**Comment by ItaloKnox** [comment]
Well, if you are going to be that careful, I'm sure I can trust you. Since @Grelo usually deals with the graphics part, maybe can he make the checks? I'll update everything when you guys are done.

**Comment by enumag** [comment]
Alright. For anyone who is interested here is the list of files the script identified as unused and deleted them.

[onikakushi.txt](https://github.com/07th-mod/onikakushi/files/981468/onikakushi.txt)
[watanagashi.txt](https://github.com/07th-mod/onikakushi/files/981469/watanagashi.txt)

**Comment by Grelo** [comment]
Its mostly correct. I picked random files from the list and checked and only ta_si_de_a1 was used in scripts from like 15 i have picked. And your script didnt delete the MG weird ones so ....i dont know.

**Comment by enumag** [comment]
Nope, ta_si_de_a1 is not used, only night/ta_si_de_a1 is. I forgot to add oni_ to the prefixed that can be deleted - fixed in new version of the compiler, thanks.
