### ISSUE TITLE
Onikakushi voices  not working for me

### ISSUE THREAD

**Issue by yagamisempai** [07th-mod/onikakushi#77]
Sorry to bother you guys but I have the same problem since the beginning, anytime I try to put onikakushi patch (ps3 sprites, cgs and voices) the voices don’t work at all and the cgs event don’t show either.

I patched the novel manually and onikakushi is the only one that gives me this problem, all the other arcs works perfectly fine after manually patching them, do I need to do something else with onikakushi?

Also I already tried with the new compressed graphics and it seems some backgrounds are missing.

Thanks for al your hard work and I hope you can help me.

![bandicam 2017-05-18 16-23-07-634](https://cloud.githubusercontent.com/assets/28794338/26244447/f5a4385a-3c8f-11e7-9fa4-399bac6e2492.jpg)

**Comment by ItaloKnox** [comment]
I replied to your email yesterday. What did cleaning the CompiledUpdateScripts and CompiledScripts folders do?

Also aren't you forgetting to extract the actual patch inside the game folder? [Talking about this](https://github.com/07th-mod/onikakushi/releases/latest).

**Comment by gagantous** [comment]
did you used the pirated one ? i mean the game @yagamisempai

**Comment by enumag** [comment]
Ancient versions of Onikakushi didn't have some of the features our patch needs to work. A pirate copy could indeed have such issues if it is from day one when the game was released.

**Comment by enumag** [comment]
@yagamisempai Did you manage to get the voices working with the latest official version from Steam or MangaGamer?
