### ISSUE TITLE
Event Blocking in onik_010.txt

### ISSUE THREAD

**Issue by magiruuvelvet** [07th-mod/onikakushi#79]
In found a event blocking issue in the file `onik_010.txt`. I was able to bypass it and continue the game.

I temporarily commented out this 2 lines
```
1530    DisableWindow();
1531    DrawBustshotWithFiltering( 3, "Tie_def", "left", 1, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 300, TRUE );
```
The game actually stopped at `DrawBustshotWithFiltering`.

I made the last update about 1 day ago, v2.5.1

Regards

**Comment by enumag** [comment]
Sounds like a missing sprite issue. Can you check your CG and CGAlt directories if there is Tie_def.png?

**Comment by ItaloKnox** [comment]
Just to make sure this is a snapshot from the current patch:
![firefox_2017-06-04_06-01-37](https://cloud.githubusercontent.com/assets/4702556/26760308/484218b8-48eb-11e7-813d-0d2df6b70590.png)

Doesn't seem to be a problem in our end, if you detail the installation steps you followed it would help us a lot.

**Comment by magiruuvelvet** [comment]
I followed the instructions as on this page https://github.com/07th-mod/guide/wiki/Part-1---Voice-and-Graphics-Patch

I just checked the assets. I have 2 files named `Tie_def.png`, one in `GC` and one in `GCAlt`. The files doesn't seem to the corrupt.

**Comment by enumag** [comment]
Did you manage to fix it? If not, can you try reinstalling the game and the patch.

**Comment by magiruuvelvet** [comment]
Sorry for late reply.

I finished the first episode already, and no I never managed to fix it just workaround it by removing those event breaking lines. Don't know what's happening here. The images files are in place and working :confused:

**Comment by enumag** [comment]
Do you have a save file somewhere close to the problem?

**Comment by magiruuvelvet** [comment]
Unfortunately not.
