### ISSUE TITLE
ADV Mode

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/onikakushi#86]
Text will go under the screen, voices stops working and some BG won't display properly.

I used Onikakushi.Voice.and.Graphics.Patch.v3.0.0 
![adv1](https://user-images.githubusercontent.com/22724316/28246067-d45d4b08-6a13-11e7-8a8f-86e5ae5fd645.png)

**Comment by enumag** [comment]
Did you use the installer or manual installation?

**Comment by Kamlingen** [comment]
I manually installed cg and voices

**Comment by enumag** [comment]
Download and apply this patch. I switched branches just a few minutes ago. https://github.com/07th-mod/onikakushi/archive/master.zip

**Comment by enumag** [comment]
Oh and delete everything in the CompiledUpdateScripts directory.

**Comment by Kamlingen** [comment]
Still got the problem(Deleted everything in CompiledUpdateScripts)

Everything workes fine when i rollback to patch v2.5.1 (Except the filter)

**Comment by enumag** [comment]
Looks like we will need to update our installation guide. You're supposed to download and apply these three files (in this order):

- https://github.com/07th-mod/resources/releases/download/Nipah/Onikakushi-CG.zip
- https://github.com/07th-mod/resources/releases/download/Nipah/Onikakushi-Voices.zip
- https://github.com/07th-mod/onikakushi/releases/download/v3.0.0/Onikakushi.Voice.and.Graphics.Patch.v3.0.0.zip

And then clean CompiledUpdateScripts.

**Comment by Kamlingen** [comment]
I did what you said in the post above with a fresh installation of Onikakushi and the problem still persist

**Comment by enumag** [comment]
Huh that's really odd. It works fine for me. Do you have an up-to-date version of the base game? Can you upload your output_log.txt file? (It is in the same directory as StreamingAssets.)

**Comment by Kamlingen** [comment]
[output_log.txt](https://github.com/07th-mod/onikakushi/files/1150933/output_log.txt)

**Comment by enumag** [comment]
According to the log, there was a small issue in one of the scripts (https://github.com/07th-mod/onikakushi/commit/9163ab272f91dc013f53e18f7bea3f9cb5bd8cd7). Try reapplying https://github.com/07th-mod/onikakushi/archive/master.zip.

**Comment by Kamlingen** [comment]
That worked 👍

**Comment by enumag** [comment]
@ItaloKnox I think we need to release 3.0.1 because of this.

**Comment by ItaloKnox** [comment]
I'll push it asap.

**Comment by ItaloKnox** [comment]
Done!
