### ISSUE TITLE
Hinamizawa overview improvement

### ISSUE THREAD

**Issue by P-Chang** [07th-mod/onikakushi#88]
I tried port effect of console. bit buggy and it need more adjustment.
How do you think it ?

http://www.dailymotion.com/video/x5uuqvb

I don't know why. daiymotion make my video look like a shit.

progress(making and debugging):
chapter1 : done
chapter2 : undone
chapter3 : nothing
chapter4 : done
chapter5 : nothing

**Comment by ItaloKnox** [comment]
I like it. If you keep improving it I think we can include it in the patch. Though I'm leaving the decision to @enumag.

About recording the video, I suggest you use [OBS Classic](http://obsproject.com/) to get a good resolution video. To upload you can use [gfycat](https://gfycat.com/upload) as well.

I'll be looking forward to the final version. 👍

**Comment by enumag** [comment]
Wow. How did you make it? I'm all for including this.

**Comment by P-Chang** [comment]
@ItaloKnox 
Thank you I'll improve it!

@enumag 
After I realize that end bool of draw and move function are wait for next draw, It is really simple.
Most hard part is I was trying copy and paste for coroutine and loop that never work lol.

Many of grep and decompile Assembly-CSharp.dll with Just decompile were helped me.

source is here.
http://www.mediafire.com/file/59vo89n79yn0i6n/overviewtest.rar

Please backup your update folder. it overwrite onik_000 and bit break your game.
Start from Day1 and never fast clicking. Waiting mark is not apper in ADV mode with it.

My CPU is bit old and I notice that small framedrop. If your CPU faster than mine, probably faster than video.

I can't understand. Sprite of Rika-chama avoid fading.

**Comment by enumag** [comment]
Nice. I managed to get rid of Rika-chama by changing her bustshot number from 36 to 26. Maybe FadeAllBustshots does not fade all but only up to 35 or something? Anyway there is no need to use such high numbers in my opinion.

I do have quite new PC so no performance issue for me.

So... where do you want to use such effects?

**Comment by Grelo** [comment]
I think this feature will only create problems. I would like to see it but its not possible imo.

**Comment by P-Chang** [comment]
@enumag 
Thanks a lot. You fixed many issue.
There is problem that big sprite conflict another scene sprite but it solved too.

I used high numbers because toketsu script use high numbers.
But there are not over 30 layer when I look these now.



As far as I remember.

"There, Where I live now. Hinamizawa."(chapter 1)

Searching Rika-chama and Satoko with night sprite (chapter 2)

"Go back to Tokyo" with night sprite (chapter 4)

There are also Sunset sprite but I don't remember that scene use it.

It can be used in The Devil's Script (chapter 6) and End of the chapter 4 with ruins sprite.
And End of the Chapter 7 with night sprite.

Actually, It is dark effect. lol

Maybe day2 of chapter1(lunch in Furude shrine) can use it 
with Rika-chama and Satoko but probably it needs some BG swap or with Rena.

Cross of two character is sometimes used in answer arc.

**Comment by enumag** [comment]
@P-Chang That's more places than I expected. But if you want to do this many cases, I won't stop you. For now could you make first one or two so that we can see how it looks in the game in the place where it is supposed to be?

**Comment by P-Chang** [comment]
@Grelo 
Sorry. I can't understand what you said enough.
Because my English skill is really crap(because my comment is too long).
Probably I have many misunderstanding.

What "it is not possible to make it" is meaning? 
I think it is completely same after adjustment of time count.

It is only few seconds, I don't think it cause contradiction.
Rika-chama and Satoko are addition for demo.

Actually there are some problems that I should fix in code.
May be it has problem with low-end pc but my extreme downclocked rig works well.
But I think it should be has option for disable like ADV-mode.

I have no idea for UProject. Is it Umineko Mod or file of Unreal Engline?

Probably my opinion for PS3 version is nearly same. Voice and graphic is awesome but 
there are many cringe feature. I really dislike they put to vocal track on Akasaka scene, and 
crappy cut scene for K vs Rena. But I think almost of graphical feature is awesome.

**Comment by P-Chang** [comment]
First one is "There, Where I live now. Hinamizawa."(chapter 1) certainly.
Second is chapter 2 or 4 but it need more adjustment.

At first it is skipable with fast clicking but I'm not big fan of there are many same feature in one game.

QTE of Resident Evil 5-6 (Wow, Devs really want to show us QTE.)
Batmobile of Batman AK (Hmm, batmobile again. I want to beat Arkham Knight in combat.)
Hacking of AC BlackFlag (I just bought it for play as pirate.)

I think 1 or 2 in one chapter is good, 3 is bound.
But I want to know what scene is you expected. Thank you for you like it :)

**Comment by Grelo** [comment]
@P-Chang
Don't worry i was just ranting for the most part. 
But please make these effects exactly like they are in PS3 version and in exact same places. Not "I like it so will put them here". Good luck, i believe you can help us make the best version possible :).

**Comment by P-Chang** [comment]
@Grelo 
There are play voice function(may be separated with BGM and SE) and wait for voice function.
If we can handle it, probably we can make lip-sync. But my knowledge of coding is really noob, I have no idea for it.

All function that I use for overview improving are already used in vanilla for different type effect.
All I did is only re-use it. lol

I'm not corder. I'm just merger of TES and STALKER MOD for playing my fav at once. 

![playvoice](https://user-images.githubusercontent.com/29869319/28667189-6ca80de0-7305-11e7-9b97-1eb7a0fe08cb.png)

**Comment by Grelo** [comment]
I dont have knowledge about this either but @enumag is hiding some secret move to make it all work.

**Comment by P-Chang** [comment]
Awesome

**Comment by enumag** [comment]
@Grelo 😄 😈  You really made me laugh with this one. While your confidence in my abilities is nice to hear, I'm unfortunately not hiding anything. In fact all of my scripts I wrote to make these patches better are here on GitHub too. But sure I'll see what I can do.

@P-Chang That screenshot with all the methods the engine has and their implementation is quite surprising. I assume you somehow decompiled the engine to get this? Is there a way to edit some parts of the code and compile it back? Can you teach me how to do this? It would really help us not only with lip-sync but with many other things as well. The best thing would be if we could add our own functions as well.

**Comment by P-Chang** [comment]
@enumag 
http://www.telerik.com/products/decompiler.aspx
decompiler is here.
It works with VisualStudio(I installed 2017), Unity option(may be it is not required ).

Thankfully decompile is really easy that like I can.
Install, open, files, / HigurashiEP**_Data/Managed/Assembly-CSharp.dll, End

I found it in any Unity game modding forum(Sorry, I don't remember).
He said hook is easier than modern complex AAA games and say nothing to recompile.
and if he talking about recompile, I really can't understand. lol

Higurashi use Buriko Library. I hear that it is second party of MG.

Please, uncover the code. It is my only desire.

**Comment by enumag** [comment]
Oh my. The last time I worked with C# and VisualStudio was like 5 years ago and even then I only knew the basics. This will be tough. I'll have a look but probably only when I'm done with Tatarigoroshi. Although with my vacation now and a secondary job starting in august I'm really not sure when I'll find the necessary time. Hopefully in september but I dare not say which year. Anyway it is nice and could help us a lot in the long-term. Thanks!

@ItaloKnox @DoctorDiablo Do you guys have any C# experience?

**Comment by P-Chang** [comment]
and anyone know the

{ "chie", 0 },{ "eiji", 1 },{ "kana", 2 },{ "kira", 3 },{ "mast", 4 },
{ "mura", 5 },{ "riho", 6 },{ "rmn_", 7 },{ "sari", 8 },{ "tika", 9 },{ "yayo", 10 }

What game have these character?

**Comment by ItaloKnox** [comment]
@enumag None at all. I can pretend I know Python and Lua, but C# and C++ are mysteries for me. I know a few C# programmers but honestly they don't have the time to help us. 😞

**Comment by DoctorDiablo** [comment]
I've used a lot of C#.  I'll give this a look in a day or two and see what I can do.

**Comment by enumag** [comment]
@DoctorDiablo Awesome! 👍 

@P-Chang Could I ask you to upload the decompiled source code? I'd like to have a look at how are some things implemented and what the engine is capable of.

**Comment by P-Chang** [comment]
@enumag 
http://www.mediafire.com/file/barlf7wlowdrggo/Source.rar
here

**Comment by enumag** [comment]
@P-Chang Thank you!

**Comment by P-Chang** [comment]
@ItaloKnox 
Thank you for tell me OBS and gifycat. I can make video that is better than previous one.
@enumag 
@Grelo 

time count and draw adjustment, and putting on correct scene is finished.
previous demo is really my mistake. that is more gorgeous than this.
it is exactly 4 layer separated animation but many guys will think it is 1 layer scroll. lol
but this is that i targeted.


simple sample:
https://gfycat.com/gifs/detail/PresentDigitalAnole
![](https://thumbs.gfycat.com/PresentDigitalAnole-size_restricted.gif)



Detail and 1080p video:
http://www.dailymotion.com/video/x5v49se


file:
http://www.mediafire.com/file/wrslj4id9sny8ot/overviewbeta.rar


start from day1 and skip to scene that K get out of train. 

main folder is inscript. callscript is still glitchy. it is for someone that help me.
In video, I disabled voices because these are noisy in skip mode. it is not bug.

it works correctly and doesn't break other scenes on consistent playing and load another scene.
but there are still some problems that i must fix is remaining...

known issue:

1. if you load savegame or chapter that before animation start, 
after you saw this animation, some sprite (in animation or not) will be broken after you see animation again.

it never happen without constant loading.

using skip mode some minuets in another scene will fix it.
reason is probably I deleted many draw function that previous demo has for reset sprite, because I think problem was fixed.
I think fade is just fade not reset.


2.in this case, backgrounds protrude fadescene and sprites of chapter end.
engine never change aspect ratio of image and it doesn't draw 16:9 accurately.

i tried with new black.png that was bit increased width but i couldn't fix.
this is common in other games and mods that use 2D sprites for rifle scopes.
it is not big problem now.

3.In callscript version, starting from chapter select or new game worked but 
starting from savegame cause freezing. because game lost valuable that is used in ADV-Mode.

selecting chapter before loading savegame fix it.

I tested with simple script like

void main()
{

	DrawBustshot( 3, "re_se_wa_a1", 160, 0, 0, FALSE, 0, 0, 0, 0, 0, 0, 0, 20, 200, TRUE );

}

it happened too, and i tested _meak_ep_02.txt that use &toketu in meakashi, and same thing happened.
meakashi use too many callscript but scene that use &eye have no issue as far as i checked.
it is strange and i have no idea for it. and callscript is best but it is not must. it is only report for ADV-mode.

Exception: Unable to GetMemory the variable with the name AdvMode
  at Assets.Scripts.Core.Buriko.BurikoMemory.GetMemory (System.String name) [0x00000] in <filename unknown>:0 

  at Assets.Scripts.Core.Buriko.BurikoVariable.IntValue () [0x00000] in <filename unknown>:0 

  at Assets.Scripts.Core.Buriko.BurikoScriptFile.CommandIf () [0x00000] in <filename unknown>:0 

  at Assets.Scripts.Core.Buriko.BurikoScriptFile.Next () [0x00000] in <filename unknown>:0 

  at Assets.Scripts.Core.Buriko.BurikoScriptSystem.Advance () [0x00000] in <filename unknown>:0 

  at Assets.Scripts.Core.GameSystem.Update () [0x00000] in <filename unknown>:0

**Comment by P-Chang** [comment]
Sorry. I missed it.
https://github.com/07th-mod/meakashi/issues/13

**Comment by P-Chang** [comment]
knownissue 1 is solved.
it seems like ready for including patch officially

I'll start the stress test.

**Comment by DoctorDiablo** [comment]
So I took a look at the C# code.  I wasn't able to compile it, but I did learn some things by looking at it.  There's a list of global variables in BurikoMemory.cs.  Looks like each chapter has its own list of globals and there are some differences between each chapter.  [onikakushi_globals.txt](https://github.com/07th-mod/onikakushi/files/1195663/onikakushi_globals.txt)
  We might be able to repurpose one of the unused ones as a global flag for AdvMode.  And here are a couple I think we can make use of:

- GWindowOpacity  - Controls opacity of the message window
- GHideButtons - Hides the UI buttons in the corner
- GArtStyle - Determines if new or original sprites are used

Also, I found a list of functions in BurikoOperations.cs that can be called from our script files.  I didn't see anything particularly useful in there, but here's the list.
[ScriptFunctions.txt](https://github.com/07th-mod/onikakushi/files/1195668/ScriptFunctions.txt)  We might be able to use the PlayVoice function instead of PlaySE for voice files, which would allow us to control voice volume independent of sound effects volume.  Probably more trouble than it's worth though.

**Comment by P-Chang** [comment]
@DoctorDiablo 
Sorry. my comment have lack of fact.

Probably, we can't compile from sorce code(I can't understand reason)
But we can edit with dnSpy and ILSpy and Just decompile (ILSpy and JD needs plugin)

Playvoice is broken until chapter 4. MG fix it in chapter 5.
I notice it in
https://github.com/MyLegGuy/HigurashiSEToVoice

I mereged it with dnSpy, playvoice worked in chapter1.
And I tried add Globalflag. it works as int Advmode, but maybe it can't work as Line_modespecific.
Glabalflag can't use as Strings ( or I didn't understand enough. )

and I didn't understand C#, my dll is completely broken after next edit.

dnSpy is good in editing
ILSpy is good in viewing
JD is good in serching

As I used these.



All that I found.

dnSPY:
https://github.com/0xd4d/dnSpy
https://www.youtube.com/watch?v=v7hYmNujfXM

ILSpy:
http://ilspy.net/
https://www.youtube.com/watch?v=-BJUkne8TDY

JustDecompile
http://www.telerik.com/products/decompiler.aspx

**Comment by enumag** [comment]
@P-Chang Your long posts are kind of difficult to understand for me, really sorry about that. Can you give me a summary? What is the current status of this? Do we have something to put into the next version of Onikakushi?

**Comment by P-Chang** [comment]
@enumag 

Sorry. I can't understand what I wrote in myself too lol.
Developing for onikakushi is finished. and gamebreaking glitches are already solved.

It works fine in my fork repository for testing dll.
I'll PR after you refresh master branch.

**Comment by enumag** [comment]
What do you mean by "refresh master branch"? The PlaySE -> PlayVoice + global flags changes from your branch?

**Comment by P-Chang** [comment]
Almost right.
I'll PR after master branch become ready for dll.

Will you use my branch? I thought you update master branch with your new syntax.

**Comment by enumag** [comment]
I'll check your branch for what to do but I'll do the changes by other means (https://github.com/07th-mod/higurashi-patch-compiler).

**Comment by enumag** [comment]
I went over your branch to see what changes I should make:

- Replace init.txt
- Delete the initializing section `int AdvMode;` + few lines in each script.
- Replace PlaySE with PlayVoice, drop the last parameter.
- Change `if (AdvMode) {` to `if (GetGlobalFlag(GADVMode) == 1) {` (possibly `if (GetGlobalFlag(GADVMode)) {`)
- Similarly change `if (AdvMode == 0) {`
- Change `Line_ModeSpecific` to `GetGlobalFlag(GLinemodeSp)`

Did I miss anything?

-----

I was thinking about using the local variables and init them with

```
int AdvMode = GetGlobalFlag(GADVMode);
int Line_ModeSpecific = GetGlobalFlag(GLinemodeSp);
```

but that probably would not works with your keyboard shortcuts, right?

**Comment by P-Chang** [comment]
These are right.

and I didn't tested keyboard shortcuts with
int AdvMode = GetGlobalFlag(GADVMode);
int Line_ModeSpecific = GetGlobalFlag(GLinemodeSp);

because int of this engine is really weak.

**Comment by P-Chang** [comment]
@enumag 
And It is necessary to invert the position of PlayVoice and NameDialog.
Because Namedialog wait voice in AutoMode.

I think you change master in your hand is more safe because you completely know the ADV-Mode.
but I can easily make changes with regular expressions, so if you use my branch I have no objection to it

**Comment by enumag** [comment]
@P-Chang You mean the line with name should go before PlayVoice? I'll need to be careful about that, script might not be able to do it automatically everywhere. Thanks for pointing that out.

**Comment by P-Chang** [comment]
@enumag 
It is like
	if(GetGlobalFlag(GADVMode) == 1) { OutputLine("<color=#f0953d>レナ</color>", NULL, "<color=#f0953d>Rena</color>", NULL, Line_ContinueAfterTyping); }
	PlayVoice( 3, "s19/02/990200228", 256 );
	OutputLine(NULL, "「一応ね、体育の時間は校庭で体を動かすのだけが決まりなの。」",
		   NULL, "\"The only rule was that we have to stay on school grounds while exercising.\"", GetGlobalFlag(GLinemodeSp));
	if(GetGlobalFlag(GADVMode) == 1) { ClearMessage(); } else { OutputLineAll(NULL, "\n", Line_ContinueAfterTyping); }
	MODSetNVLModeInADVMode();

**Comment by enumag** [comment]
Wait a sec. What is `MODSetNVLModeInADVMode();`?

**Comment by P-Chang** [comment]
oh, misstype.

It is that I making now.
I know you said remade some line revert NVL Mode

it is for it.but glitchy now

**Comment by enumag** [comment]
@P-Chang Where can I find the correct init.txt? I thought there would be more flags there than in the [init.txt](https://github.com/P-Chang/onikakushi/blob/master/Update/init.txt) from your branch.

**Comment by P-Chang** [comment]
@enumag 
here.
[init.txt](https://github.com/07th-mod/onikakushi/files/1237226/init.txt)

Overwriting on updating may have confused you, sorry.

**Comment by enumag** [comment]
@P-Chang This is still happening some time in the future, just on-hold for now, right? No rush, I just want to know the current status of all our issues.

**Comment by P-Chang** [comment]
@enumag 
Almost of developing is finished. I implement it for chapter that need it until next release.
I close this issue.
