### ISSUE TITLE
Use NVL mode again, after instal ADV mode

### ISSUE THREAD

**Issue by gagantous** [07th-mod/onikakushi#92]
How do i change it back to NVL mode even after i install the patch for ADV mode ?

**Comment by ItaloKnox** [comment]
At the start of each script you will find the line ``AdvMode = 1;``. You have to change the number to ``0`` in each script for that.

I suggest you to roll back to the previous version or wait while we work in the new version that lets you switch between modes inside the game with a single button.

**Comment by ItaloKnox** [comment]
By the way, you have to clean the ``CompiledUpdateScripts`` folder after you change the scripts. If you don't the game will load the ADV mode again.

**Comment by enumag** [comment]
+ you need to switch the windo_filter.png image with one from a previous version.

**Comment by gagantous** [comment]
okay i will try this , thanks

**Comment by ItaloKnox** [comment]
Yes, if you really want to play using the NVL mode you should just roll back to the previous version. The update that allows you to switch between modes easily should come out in the following weeks. We don't have the date yet but hopefully it'll be here by the end of the month.

**Comment by netugi** [comment]
Just curious of what it means to clean the CompiledUpdateScripts folder. I've manually changed all the AdvModes to 0.

**Comment by ItaloKnox** [comment]
You can find it inside the StreamingAssets folder. Go inside the CompiledUpdateScripts folder and delete everything inside there.

Also don't forget to swap the ``windo_filter.png``. [You can download it here](https://user-images.githubusercontent.com/4702556/27495090-ea840baa-5826-11e7-8e14-652df5f60bcf.png), just rename it. This file should go inside the CG folder.

**Comment by netugi** [comment]
It seems to be working fine now, thanks!
