### ISSUE TITLE
Onikakushi ADV mode do not work for me 

### ISSUE THREAD

**Issue by yagamisempai** [07th-mod/onikakushi#93]
Sorry to still bother you but the new and latest patch for onikakushi did not work for me i mean i install it  following the indications on the instal wiki and for watanagashi to meakashi it works perfectly fine, only with onikakushi did not work, i have the same problem since the begening or the voice and ps3 patch proyect.

Is there something diferent with onikakushi?
Like i said the patch works perfectly fine with the other arcs but only onikakushi gives me the problem
(the game do not start and it is just a black screenand do not do anything)
I already re install it from my steam acount and still the same, I have an old version of the onikakushi patch and it works and have the voices but still some cg events dont show  and this old patch works because someone puts a link of his StreamingAssets folder because like i said since the begining i had the same problems with onikakushi and only with onikakushi cause all other arcs work peferctly fine.

once agai sorry to bother you guys but really i dont know what else can i do.
these are the cgs that are missing from my old onikakushi patch and like i said before when i put the new patch the game just go black screen and anything happends and this is only with onikakushi.

![002a](https://user-images.githubusercontent.com/28794338/31533381-4155d166-aff2-11e7-8f61-f68c21d7639a.png)
![002b](https://user-images.githubusercontent.com/28794338/31533382-41789372-aff2-11e7-9930-f94f3b974ba1.png)
![031](https://user-images.githubusercontent.com/28794338/31533383-41a174b8-aff2-11e7-838c-26a24f5a1e5a.png)
![103a](https://user-images.githubusercontent.com/28794338/31533385-41bcc8bc-aff2-11e7-98ac-4525adeec01c.png)
![103b](https://user-images.githubusercontent.com/28794338/31533386-422099aa-aff2-11e7-9617-ecea4864f867.png)

**Comment by ItaloKnox** [comment]
Have you tried installing the patch using our installer? I also suggest you uninstall the game and clean the game folder afterward, maybe that will solve the issue. When you uninstall the game it will often leave some stuff behind, so the best thing is to manually clean everything before reinstalling it. Also, try going to ``%appdata%\Mangagamer\higurashi01`` and clean everything inside this folder. Remember that this will delete your savegames and menu configs.

**Comment by yagamisempai** [comment]
is that flder on the steam folder?
cause i only find appcache

**Comment by ItaloKnox** [comment]
Open any Windows Explorer window and put this in the address bar: ``%appdata%\Mangagamer\higurashi01``. You should be sent to the folder automatically.

The game folder should be inside the ``steamapps\common`` folder.

**Comment by enumag** [comment]
ping @yagamisempai

**Comment by enumag** [comment]
@yagamisempai Any update? You know you always come up with some very strange problem noone ever experienced and then you stop responding soon after. We can't help you like this... I'll have to close this issue if it's inactive for another week.

**Comment by Mangleus** [comment]
I have the exact same problem under win8,1. And only with onikakushi.

The original Assembly-CSharp.dll (1,221 Kb) made the thing at least to start up but the backgrounds will then be in a square in the middle rather than widescreening on my 1366x768 laptop. With the patched Assembly-CSharp.dll (1,166 kb) it is just a black screen. I have tried every imaginable constallation emptying various folders under /user and scrips/update and so on.

In the output-log.txt i see countless of:

NullReferenceException: Object reference not set to an instance of an object
  at *whateverwhateverwhatever* () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

Maybe .NET related, but i have no clue really. I have and will not update my .NET since it turns this laptop into a snail. All the other higurashi's works fine on this system but not being able to get through the very first one sort of halt things....  I also tried out some of the experimental tweaked versions on Assembly-CSharp.dll found elsewhere but with no joy. Just black screen.

I would be overjoyed if there would be some small file that i could feed my onikakushi that would make it work as well as all the other patches for the rest of Higurashi on this system.

**Comment by enumag** [comment]
@P-Chang Any idea what might be different about the Onikakushi DLL?

**Comment by ItaloKnox** [comment]
@Mangleus Can you answer a few questions first?

* Are you running the game on Steam or DRM-free?
* Does the game work fine without our patch?
* Did you try both releases [v4.0.0](https://github.com/07th-mod/onikakushi/releases/tag/v4.0.0) and [v4.0.1](https://github.com/07th-mod/onikakushi/releases/tag/v4.0.1)?
* Did you clean the ``CompiledScriptsUpdate`` folder every time you changed .dlls?

**Comment by enumag** [comment]
@Mangleus Also did you install our patch using the installer or manually?

**Comment by Mangleus** [comment]
Does the game work fine without our patch?
Yes, and after the patch i tried the old Assembly-CSharp.dll, and as mentioned above it runs but not in widescreen.

Did you try both releases v4.0.0 and v4.0.1?
Yes,I did. And older ones/experimental ones as well.

Are you running the game on Steam or DRM-free?
All i wish say on this topic is that i during a few days now have tried many different variations, some related to steam and others related to non-drm.

Did you clean the CompiledScriptsUpdate folder every time you changed .dlls?
Yes this is what i do.

Also did you install our patch using the installer or manually?
The connection/firewall stuff that i am behind right now do not allow the installer, but yes, previously i tried the installer also which only resulted in a black screen.

**Comment by ItaloKnox** [comment]
>  All i wish say on this topic is that i during a few days now have tried many different variations, some related to steam and others related to non-drm.

That's not very helpful and not exactly what I asked.

**Comment by P-Chang** [comment]
@enumag 
Sorry for my late reply.

Almost codes for chapter2-5 were merge from onikakushi. 
So, if I failed in onikakushi, entire chapter should be broken, especially watanagashi.

But in the fact, engine of onikakushi is most vulnerable.

I'm bit confusing. @yagamisempai  had same issue before mod use my dlls. so, I think it is no related in my dlls. but @Mangleus report this after mod use my dlls.

@Mangleus 
I want to ask you

1. Can you run vanilla game?
2. Can you run previous version that doesn't have dll tweak like v3.0.1 or earlier.
3. Please upload full output.log. I can't know anything without this.

Although, If you have time, please try vanilla game with tweaked dll.

**Comment by P-Chang** [comment]
And I curious about this line.

> Did you clean the CompiledScriptsUpdate folder every time you changed .dlls?
> Yes this is what i do, but that being said, most of the time a CompiledUpdateScripts folder do not even get created when the black screen halts everything.

https://github.com/07th-mod/onikakushi/issues/87
Screenshot that was uploaded by @yagamisempai  is same as case that I deleted `CompiledUpdateScripts` in fault.

I assume that some user are mistakenly "deletting file in CompiledUpdateScripts" and "deleting CompiledUpdateScripts folder"

**Comment by P-Chang** [comment]
I remember that output.log are not stored in game folder. and I searched unity reference.


```
macOS | ~/Library/Logs/Unity/Player.log
-- | --
Windows XP | C:\Documents and Settings\username\Local Settings\Application Data\CompanyName\ProductName\output_log.txt
Windows Vista/7 | C:\Users\username\AppData\Local\CompanyName\ProductName\output_log.txt
Linux | ~/.config/unity3d/CompanyName/ProductName/Player.log
```

log file that we call like output.log are probably player.log

**Comment by Mangleus** [comment]
I am sorry, but my (real) life is now much to busy to be able to put any more time into this. It is not possible now. I wish you all good luck with your very nice project.

**Comment by enumag** [comment]
I think this issue is outdated and most probably won't appear again. If it does please open a new issue.
