### ISSUE TITLE
The menu GUI didnt fit the whole screen

### ISSUE THREAD

**Issue by gagantous** [07th-mod/onikakushi#95]
![easd](https://user-images.githubusercontent.com/24579576/34328880-7673517e-e8a1-11e7-8863-592781bb3353.png)

Why does the cg looks like this ?

**Comment by gagantous** [comment]
okay seems i have fixed that but the menu did not fit with the entire screen ( se the red mark )
![untitled](https://user-images.githubusercontent.com/24579576/34329000-cbaea64a-e8a4-11e7-84b0-ee140d28e347.png)

**Comment by enumag** [comment]
Yep, that's a 16:10 issue. It can probably be fixed by manipulating some values in init.txt. @P-Chang might now which values. I'd have to do it trial and error way but I don't have access to my 16:10 monitor right now.

**Comment by gagantous** [comment]
@enumag  okay i will wait for @P-Chang

**Comment by P-Chang** [comment]
Sorry, I have only 16:9 and 4:3 monitor. and my rig can't use 16:10 aspect ratio.

[init.txt](https://github.com/07th-mod/onikakushi/files/1585793/init.txt)
Old Gui pos that we used when we didn't use patched DLL.

[init.txt](https://github.com/07th-mod/onikakushi/files/1585798/init.txt)
updated aspect ratio to 16:10. but I can't know it works well

**Comment by gagantous** [comment]
@P-Chang  the screen still the same........

**Comment by gagantous** [comment]
even when i tried the game  at 640x480 resolution, no different
![2](https://user-images.githubusercontent.com/24579576/34355549-0ff03a84-e9eb-11e7-8133-47dc344c2916.PNG)

**Comment by gagantous** [comment]
but when i tried this [init.txt](https://github.com/07th-mod/onikakushi/files/1585793/init.txt)
it goes like this 
![14](https://user-images.githubusercontent.com/24579576/34355732-8e4e05cc-e9ec-11e7-8512-ea3a9167c422.jpg)

**Comment by gagantous** [comment]
@P-Chang  which variable/parameter in init.txt should i change to make this works ?

**Comment by enumag** [comment]
@gagantous Try the original file with `SetGUIPosition` 100 or so. That would be my guess but I can't verify it right now.

**Comment by gagantous** [comment]
@enumag  okay it's fit just fine, but the cg now have like a black bar in both side ( up side and bottom side ) screen

**Comment by enumag** [comment]
@gagantous Can't help you any more right now. Post here the init.txt file you're currently using. I'll try it on my PC when I get home which should be in 4 days or so.

**Comment by gagantous** [comment]
oh i just realized, the black bar that i said earlier will occurs when i set the windows game in fullscreen ( whic is (1280x720), and and then i changed again the windows game screen to minimum sized ( 640x480p ). Nothing weird at this point. After that i tried to set the screen game into 1280x720p again ( in fiullscreen of course ) and the black bar will appear

**Comment by P-Chang** [comment]
SetScreenAspect("0.625"); is windows size.

(16:10)`10 / 16 = 0.625`
(16:9)`9 / 16 = 0.5625`
(4:3)`3 / 4 = 0.75`

I forgot to say that window system of game is bit frustrating.
It need relaunch sometimes and some press of `Alt+Enter`

Try my second one and `relaunch and Alt+Enter`
[init.txt](https://github.com/07th-mod/onikakushi/files/1585798/init.txt)

if it become like this it is ok.
![blackbar](https://user-images.githubusercontent.com/29869319/34358976-bd6e219c-ea97-11e7-9d47-61058da53ead.png)

**Comment by P-Chang** [comment]
Sorry, I completely misunderstand 16:10 and 21:9

**Comment by P-Chang** [comment]
[init.txt](https://github.com/07th-mod/onikakushi/files/1587497/init.txt)

Tested in 1200p. I think this one could fit int 16:10

blackbar in windowed mode is un-fixable.

**Comment by gagantous** [comment]
This one looks promising, no blackbar appear. even when i used the windowed mode. thanks @P-Chang 

![15](https://user-images.githubusercontent.com/24579576/34359613-3b0fe46c-ea0e-11e7-81bb-ef243bac7d5d.png)

**Comment by gagantous** [comment]
The update patch that i got have the `SetScreenAspect("0.5625");` that's why i got the blackbar in my screen game

**Comment by P-Chang** [comment]
Probably black bar appear in mismatched screen. good.

**Comment by gagantous** [comment]
@P-Chang @enumag  could you suggest me a good title for this thread ? i am not a native speaker, so i dont know how to explain my problem in my title

**Comment by P-Chang** [comment]
I can't I'm not native speaker too.

**Comment by gagantous** [comment]
oh okay..

**Comment by enumag** [comment]
Well I'm not a native speaker either. But I'd use something like "Buttons overflowing in fullscreen mode on 16:10 monitor"

**Comment by enumag** [comment]
Also could you upload the final init.txt you're using? We should probably add it to our FAQ.

**Comment by P-Chang** [comment]
[init.txt](https://github.com/07th-mod/onikakushi/files/1587497/init.txt)

Probably it is. All that I changed is

```
	SetScreenAspect("0.625");
	SetGUIPosition(100, 0);
```

And All mode WindowPosX

`
	-100, //WindowPosX
`

**Comment by gagantous** [comment]
@P-Chang  yup, that one
