### ISSUE TITLE
Installer issue

### ISSUE THREAD

**Issue by Kamlingen** [07th-mod/onikakushi#97]
The installer doesn't download Onikakushi.Voice.and.Graphics.Patch

**Comment by ItaloKnox** [comment]
I believe your computer is having issues using Powershell? Try going into the ``temp`` folder, delete the file ``local.txt`` and run the file ``updater``. If it doesn't download anything then you need to install the scripts manually.

**Comment by Kamlingen** [comment]
Changing it to the original steam folder seems to have fixed it for me.
