### ISSUE TITLE
Improving the GUI

### ISSUE THREAD

**Issue by Nozoki17** [07th-mod/onikakushi#99]
Well I'm not sure if it's the right place to do it, or if it's in the aim of the mod, but I had some ideas to improve the User Interface while working on my translation and on the tips icons. Really not the most important (nor seen in any previous releases of higurashi for one), but felt quite nice in-game when I toyed with them.

First idea: Make a better version of the logo, it hasn't changed since the original release and feels a bit unpolished compared to the rest of the graphic assets used. My idea was to make an inbetween this original logo and the one from Hou. (Here's an example closer to the og french logo, but I can work it out to match the english one)

http://steamcommunity.com/sharedfiles/filedetails/?id=1107639120

Second idea: Add name chapter for the logo used between days in-game, there's two instances of the logo in the files (one for menu and one for the end of a day) and it looked really cool when I toyed with it in game

http://steamcommunity.com/sharedfiles/filedetails/?id=1107638751

Third idea: Unique scenario screens for each chapter, more related to it while being very subtle to add more variety instead of having the moon each time (example: for Onikakushi, I used the riverside where Keiichi learns about the curse)

http://steamcommunity.com/sharedfiles/filedetails/?id=1259769563

And finally, fourth idea: Use black and red menu items to be closer of the menus of the ps2 version, it looks far more nicer than the bright blue ones. (here are some really quick tests I made in photoshop, haven't tried it ingame yet)

![mainui](https://user-images.githubusercontent.com/35120334/34640566-eb8ef6c2-f2f4-11e7-8a9a-11440a9e7e27.png)

![configbg](https://user-images.githubusercontent.com/35120334/34640567-f44fed5c-f2f4-11e7-80cf-6f6103d37915.png)

**Comment by enumag** [comment]
While UI improvements was never on our list I don't think it's out of scope for our mods. We just add whatever improvements we can think of. This might be a good addition.

Can you post some screenshots of the new GUI in the game? I can't imagine how it would look.

Personally I like all the ideas you posted here. What do you think @ItaloKnox?

**Comment by Nozoki17** [comment]
I'll try to recompile the game with those (for some reason I had some trouble yesterday)

And obviously, I'm willing of doing them all myself, I'm quite good with photoshop and already very familiar with Higurashi's Assets, so it wouldn't be a problem

**Comment by ItaloKnox** [comment]
I'm ok with GUI changes but I think we should wait a bit because we're getting an extra button for chinese translation. I'm afraid that will break the changes.

**Comment by Nozoki17** [comment]
![20180106223227_1](https://user-images.githubusercontent.com/35120334/34644166-971d0be6-f331-11e7-8887-eb63e9d3d32e.jpg)
![20180106223237_1](https://user-images.githubusercontent.com/35120334/34644169-99cbd03e-f331-11e7-87ae-90cc8e92c6db.jpg)
![20180106223243_1](https://user-images.githubusercontent.com/35120334/34644170-9b84d2b8-f331-11e7-86f0-30d39137e4ae.jpg)
![20180106223255_1](https://user-images.githubusercontent.com/35120334/34644171-9cf70b52-f331-11e7-88ca-c6c2aa0f7d66.jpg)
![20180106223300_1](https://user-images.githubusercontent.com/35120334/34644174-9e67e65a-f331-11e7-82ea-55037e96cade.jpg)

Here's what a very basic recoloring of the menu looks like, keep in mind that I just recolored with a filter and for the final one, I'll probably remake the buttons from scratch using darker shades.

Also, I just realised that I can't seem to find the file for buttons of the extra menu?
![20180106223153_1](https://user-images.githubusercontent.com/35120334/34644186-ea047b28-f331-11e7-9317-0e687300641b.jpg)

**Comment by InochiPM** [comment]
![logo](https://user-images.githubusercontent.com/13459080/34644568-106e4ee0-f307-11e7-9af7-0046deba2e3a.png)
I have made a better version of the Higurashi logo for Sui.

**Comment by Nozoki17** [comment]
It's the kind of thing I wanted to do, but with "Hou" to go with the current release. But it looks really sharp and good, great job!

**Comment by InochiPM** [comment]
Yeah, I'm currently making the better Hou logo in photoshop. 
I would also like to entertain the idea of changing the shape of the buttons to look more like the sui buttons more rounded and such.

**Comment by Nozoki17** [comment]
I need to take a look at how they are in Sui, for now I thought about basing myself on Matsuri but I can give it a shot

**Comment by InochiPM** [comment]
Oh also! The background part of the log, and the right click menu, would it be possable to extend the opaque gray backing to fit the whole screen while leaving the menu in the center? or moving it around to make it look nicer maybe? i have Sui on my PC and my PS3 ill have a look into the menu buttons and such in a second.

**Comment by enumag** [comment]
@Nozoki17 Would it be possible to make the red textlog somehow less "aggressive"? There is too much red in my opinion.

**Comment by Nozoki17** [comment]
@InochiPM I'll have to try, I don't know yet if those are bound to a 4/3 ratio like the background image of the tips menu.

@enumag Sure! I'll have another try tomorrow when I wake up (getting quite late here xD)

**Comment by InochiPM** [comment]
@Nozoki17 Here is the Hou logo i made. And okay, i'm hoping that its not fixed and can be stretched or at least just the back extended to the edges. 
![logo_hou](https://user-images.githubusercontent.com/13459080/34644808-96f44290-f30b-11e7-92d5-ae552cccfa50.png)

**Comment by Nozoki17** [comment]
Looks really cool, cudos to you!

**Comment by Grelo** [comment]
I think we will need the Sui one, so console arcs can use it too.

**Comment by Nozoki17** [comment]
I'd rather have something consistent rarher than something really "canon" and anyway those arcs will be modded into hou aren't they?

**Comment by Grelo** [comment]
They are not part of the Hou but yea i think @DoctorDiablo will eventually mod them all.

**Comment by enumag** [comment]
Well it depends. There is a LOT of them, especially for only one person.

**Comment by enumag** [comment]
@Nozoki17 Any progress with the backlog?

@ItaloKnox What is your opinion about the new GUI and logos? 

Does anybody know where the image for [blue buttons](https://user-images.githubusercontent.com/35120334/34644186-ea047b28-f331-11e7-9317-0e687300641b.jpg) is located and if we can replace it? Maybe @P-Chang might know?

**Comment by Nozoki17** [comment]
@enumag Sorry this week I got back to school so I haven't had much time to try it out, I'll make progress during this weekend ^^

**Comment by enumag** [comment]
@Nozoki17 There is no rush, I'm just checking the status of all current issues. Take your time and thanks for your work! :-)

**Comment by Nozoki17** [comment]
I'll probably sketch a thing or two that I thought could be nice too for menu items, instead of just recoloring them, to get some feedback before taking them to the next step ^^

**Comment by ItaloKnox** [comment]
I have no big feelings about the UI changes so if you guys are okay with it I'm also okay. It never bothered enough to want to change it.

**Comment by Nozoki17** [comment]
It's mostly just toying around a bit to see if there's something that could look better to be honest, totally optional stuff.. 

It started when I played Matsuri and saw how cool the UI looked in grey/red/black compared to the bright blue UI we got.

**Comment by enumag** [comment]
@Nozoki17 The background behind "TEXTLOG" was better in your first attempt in my opinion.

**Comment by InochiPM** [comment]
@Nozoki17 Oh that sucks, if it wasnt hard coded it wouldnt look so out of place in the middle, but good job on the text log.

**Comment by Nozoki17** [comment]
@enumag Alright, I'll try to put the other header back. What do you think of the grey though?

@InochiPM Yeah, I need to look a bit more into it to see if I can put it into a 16/9 ratio, or atleast try to fadeout the edges to see if it looks a bit better

**Comment by enumag** [comment]
@Nozoki17 The gray is ok-ish? It feels a bit dull but it's still better than the completely red background imo. I'm not quite happy with it but not sure how to improve it either.

**Comment by Nozoki17** [comment]
![20180115133735_1](https://user-images.githubusercontent.com/35120334/34943036-29e65206-f9fa-11e7-9267-38b65754dd50.jpg)

We're getting into the totally useless, but I tried to rework the logo to bring it to hd standard (1440x1080) and also doing a total makeover inspired by the logo from Sui, the manga, and the french translation

**Comment by enumag** [comment]
@Nozoki17 You sure about the "H" instead of "Hou"? It seems a bit confusing to me...

Also guys can we replace the main menu buttons somehow? I never really liked them.

**Comment by Nozoki17** [comment]
I'll try to make a version with "Hou" in it, but thanks! I also tried to redo my "interchapter" idea too, and the cool thing with these is that it's really easy to swap the text for future arcs and maybe for the console ports that could be labeled as "Extra" or something (I'm not sure about the term chapter)
![title02](https://user-images.githubusercontent.com/35120334/34946188-2a712f82-fa06-11e7-8acc-91d389d28da5.png)

As for the buttons for the Extra menu, I looked everywhere, they are nowhere to be found for now.. but the main menu should be easy as long as we keep the same dimensions for each button

**Comment by enumag** [comment]
> but the main menu should be easy as long as we keep the same dimensions for each button

That might be a problem with Meakashi. The buttons there are awfully tiny.

**Comment by Nozoki17** [comment]
Could you post a screen? I have yet to buy Meakashi so I don't know how they look.. I may be able to fix it though

**Comment by enumag** [comment]
I'm not home right now. I'll post it in a few hours.

**Comment by DoctorDiablo** [comment]
![image](https://user-images.githubusercontent.com/20390474/34949736-fcfb2dea-f9de-11e7-8392-d1f8383a62dd.png)

They're just floating text in Meakashi instead of proper buttons, but they get highlighted in red when you mouseover.

**Comment by enumag** [comment]
@DoctorDiablo Oh it's just a text? Any idea how we can change it to normal buttons? I'd assume the buttons logic is still in the engine, just not used.

**Comment by P-Chang** [comment]
![titlehigurashi-sharedassets0 assets-32](https://user-images.githubusercontent.com/29869319/34950191-caf4fe4e-fa55-11e7-8a1b-4cfa5adcdeab.png)

It's not. but I can't realize which location you dislike. lower resolution?

**Comment by DoctorDiablo** [comment]
It's also moderately annoying that they translated omake to extra in the question arcs but left it untranslated in the answer arcs.  Can we pick one and make it consistent?

**Comment by Nozoki17** [comment]
Well it'll be difficult to modify then, maybe by increasing the resolution I might be able to modify them without looking like complete trash, but even then, it will be pretty difficult. 

On a side note, I'm quite disapointed of that "new" menu (I never saw it before) I would have prefered if they at least kept consistent with the four previous arcs, or change the menu for all of them.

@DoctorDiablo With the right font I can modify it in 2 minutes, but I feel you, I'd prefer if they kept Extra instead of omake, especially since it's romaji for extra in the first place.

**Comment by enumag** [comment]
@P-Chang Well the buttons in Meakashi look awful and are difficult to point at because if their low height. They should not be so wide but should be higher - like in the question arcs...

@Nozoki17 Totally agree that they should have kept the question arcs menu. I wish we could change it in Meakashi somehow.

**Comment by Nozoki17** [comment]
Also, not really an UI but I just remembered I made steam banners for all four question arcs, both for Alchemist and Mangagamer sprites, and in japanese and english too, might be cool to include them somewhere for those who wants them.

Here's an example with Onikakushi, I might rework them a bit before releasing them though.

![onikakushi](https://user-images.githubusercontent.com/35120334/34951029-3a4633d0-fa15-11e7-85d4-628872e2867f.png)
![onikakushi](https://user-images.githubusercontent.com/35120334/34951038-3f6475f2-fa15-11e7-89b8-18ccf5ecd7be.png)

**Comment by Nozoki17** [comment]
One thing I might try with Meakashi's menu, is shorten the red overlay, because quite frankly, it looks ridiculous to have them be that long

**Comment by P-Chang** [comment]
But wait, I think they should be short. but button have full width.

**Comment by Nozoki17** [comment]
I tried a logo with a full Hou, here's a comparsion between just an H and Hou, the quality difference is because I forgot to use the scaled up version, but it'll be fixed very easily.

![20180115171216_1](https://user-images.githubusercontent.com/35120334/34951773-a04c1c10-fa17-11e7-86fd-a670b88a7127.jpg)
![20180115133735_1](https://user-images.githubusercontent.com/35120334/34951776-a23f42a4-fa17-11e7-824f-bc7cef925abf.jpg)

**Comment by jwgrlrrajn** [comment]
Regarding the backlog background, perhaps a really dark red might work? Like #4B0000?

**Comment by enumag** [comment]
@Nozoki17 Those banners look awesome! Not sure where exactly we could use them though. :-D

Hou looks good. Personally I'd try preserving the font-size of "Higurashi When they Cry" from the "H" version and making "Hou" a bit smaller. But it's not important - if you like it as is, we can keep it.

**Comment by Nozoki17** [comment]
@enumag The problem with that is that even if I extend the bar underneath the logo and recenter the whole thing, it will look _really_ big but it might be fixed if I down size a bit the whole thing.. I'll try a bit later, I spent the afternoon working on those, I'm getting a bit tired xD

**Comment by enumag** [comment]
@Nozoki17 I just feel like the Hou is too big and Higurashi too small. But it's minor thing.

**Comment by Nozoki17** [comment]
![20180115180710_1](https://user-images.githubusercontent.com/35120334/34953937-cda3bf36-fa1e-11e7-91b8-796adabc2832.jpg)

I reduced the Hou and gave back some width to Higurashi

**Comment by enumag** [comment]
@Nozoki17 LGTM 🙂 👍 :shipit:

**Comment by Nozoki17** [comment]
Alright, then I'll increase the resolution and modify a bit the effect around it to make it look the best.

Here's also an example of it being used as a chapter break (I'll reduce it a bit I think, looks wayyyy too big)

![20180115181805_1](https://user-images.githubusercontent.com/35120334/34954421-b422b312-fa20-11e7-9dec-29ace53df201.jpg)

**Comment by enumag** [comment]
Hou should be more shiny here I think.

**Comment by Nozoki17** [comment]
![20180115193534_1](https://user-images.githubusercontent.com/35120334/34956834-2f30a76c-fa2b-11e7-8510-1d07fe070484.jpg)

Tried a bit more glow and upgraded to UHD (worth it, it increase a lot the quality of the logos while being really small in size)

**Comment by InochiPM** [comment]
![logo_hou](https://user-images.githubusercontent.com/13459080/34961997-ddff56e2-fa0f-11e7-820f-5b69af39756a.png)
A couple of day's ago i re-made the Hou-logo from the japanese logo in illustrator, so its a much higher resolution version.

**Comment by P-Chang** [comment]
As a such a purist.
It looks good, but isn't it unfettered?

There are some rules, "07th expansion presents....." have to be use `Christina` font.
Black is not border it is shadows.
All character need upscale to height upscale(Japanese original was 330% upscaled).
Using Hou for ch1-8 and Rei is not correct.
Using italic make it to Umi like.
White bar is should be more big.
One part of "Kai" "Rei" "Hou" should go through white bar.

I know English version of Game, Anime, Manga using different logo and making it to nealy original is not good in everytime.

But MG English Kai font is best in my opinion(but i can't find this font).

If almost of English user don't like vanilla logo, and want to replce, I have no objection.
But Christina and using Kai as Kai, Rei as Rei, Hou as Hou is must in my opinion.

**Comment by enumag** [comment]
@Nozoki17 Maybe the Hou should use the same glow as in main menu? Not sure but it might look better - and would certainly be more consistent.

**Comment by InochiPM** [comment]
@P-Chang I know the English font it is Sei Kaisho CB1.

**Comment by Nozoki17** [comment]
@P-Chang While I agree on a lot of things that I simply didn't knew, I don't think Hou is out of place. Kai and Rei are the name of the releases, and Hou is the current one we're working on, no?

But anyway, I'll tweak it some more tomorrow, it's getting very late here ^^

**Comment by P-Chang** [comment]
@InochiPM 
Yep, you tell me few days ago. but it is QA fonts.

![end_3](https://user-images.githubusercontent.com/29869319/34962717-49227116-fa88-11e7-9f19-71c216a9609a.png)

![end_3](https://user-images.githubusercontent.com/29869319/34962702-39483a50-fa88-11e7-80f7-9f41ec9300e1.png)

@Nozoki17 
Almost of I talked is such a purist talk and some of them make it better, sorry.

We are working on is Hou is correct. it is bit complicated.
Hou is anniversary release, so product have all arks in original release.

Hou ark is Outbreak and Kamikanshi in the strict sense.

So, vanilla title logo was not changed.

**Comment by Grelo** [comment]
@P-Chang You are right. I don't like where this is going.

**Comment by enumag** [comment]
What is your input on this @ItaloKnox? Personally I don't care too much whether the logo is normal/Kai/Rei/Hou/Sui/whatever.

**Comment by ItaloKnox** [comment]
In a way, I don't really care that much about it but I can certainly understand @P-Chang's point. I agree 100% with him. To quote him: "Kai as Kai, Rei as Rei, Hou as Hou is must in my opinion". I feel the same way about the logo.

**Comment by enumag** [comment]
Sounds good.

@Nozoki17 Could you change the logo accordingly? Also could you put together all your current changes for pre-release version of onikakushi (logo, UI, tips, whatever else you wanna change)? You can of course make tweaks or even overhauls any time later, I just want to have something for the pre-release version. Even the pre-release is still a bit away though so no rush.

**Comment by Nozoki17** [comment]
Alrighty, I'll try to get the right fonts and try to be more of an hd makeover of the logo (with a size similar to what I already did, cos right now the original taking half the menu is just plain ugly)

As for the other UI items, I'll wrap up what I'm already doing, and will roll updates on it as we progress

**Comment by Nozoki17** [comment]
(Can't seem to find how to edit on mobile but when I say HD makeover of the logo, I mean the original one, instead of doing my own thing)

**Comment by InochiPM** [comment]
@Nozoki17 @P-Chang I found the second font they used for Kai, its a font called Reisho E1 (隷書E1), Its by the same company who made the font in the first games logo that mangagamer used lol. 

Its a really hard to find font, i cannot find a place to get it or purchase it thats not gonna cost me an arm and a leg.

**Comment by Nozoki17** [comment]
Even if it's not _really_ legal, I may be able to redraw the characters needed to make a font in illustrator

**Comment by InochiPM** [comment]
@Nozoki17 well the website has a previewer for the font you could put the logo words in there, screen grab it, then touch it up in illustrator with the outline tool.

**Comment by InochiPM** [comment]
[Higu-Kai_LOGO.zip](https://github.com/07th-mod/onikakushi/files/1637400/Higu-Kai_LOGO.zip)

@Nozoki17 Here, i created a font from the existing characters. Their crisp and at 300dpi, its all the english letters with a few symbols thrown in.

**Comment by Nozoki17** [comment]
@InochiPM Thanks a lot, it'll help greatly

**Comment by InochiPM** [comment]
@Nozoki17 heres the actual font file. i managed to find it a while back
[CB1.otf.zip](https://github.com/07th-mod/onikakushi/files/1648046/CB1.otf.zip)

**Comment by enumag** [comment]
@Nozoki17 We're almost ready to compile the new graphics patch. I should be able to fix all the remaing issues today. Can I ask for the gui update pack for Onikakushi pre-release?

**Comment by P-Chang** [comment]
Almost of UI tweak use another way from we did, so I prefer to do UI tweak after next release.

**Comment by enumag** [comment]
ping @Nozoki17
